(function(){NumUtil={addComma:function(a){a=""+a;var b=a.indexOf(".");0>b&&(b=a.length);for(var c=a.substring(b,a.length),d=0;d<b;d++){var e=a.substring(b-1-d,b-1-d+1);if("0">e||"9"<e){c=a.substring(0,b-d)+c;break}0<d&&0==d%3&&(c=","+c);c=e+c}return c},removeComma:function(a){if("undefined"==typeof a||null==a)return"";value=""+a;return value.split(",").join("")}};Calc={calcAll:function(a){$("#"+a).find("input.multi").attr("calced","0");$("#"+a).find("input.sum").attr("calced","0");$("#"+a).find("input.diff").attr("calced",
"0");Calc.calcSum(a);Calc.calcDiff(a);Calc.calcMulti(a)},calcSumField:function(a,b){if("1"!=$(a).attr("calced")){var c=$(a).attr("fields").split(" "),d=null;Ext.each(c,function(){var a=$("#"+b).find("[name="+this+"]")[0];$(a).is("input.sum")&&"1"!=$(a).attr("calced")&&Calc.calcSumField(a,b);$(a).is("input.diff")&&"1"!=$(a).attr("calced")&&Calc.calcDiffField(a,b);$(a).is("input.multi")&&"1"!=$(a).attr("calced")&&Calc.calcMultiField(a,b);a=$("#"+b).find("[name="+this+"]").val();if("undefined"==typeof a||
""==a.trim()||isNaN(parseFloat(NumUtil.removeComma(a),10)))return!0;null==d&&(d=0);d+=Math.floor(parseFloat(NumUtil.removeComma(a),10))});null==d?$(a).val(""):$(a).val(NumUtil.addComma(""+Math.floor(d)));$(a).attr("calced","1")}},calcSum:function(a){$("#"+a).find("input.sum").each(function(){Calc.calcSumField(this,a)})},calcDiffField:function(a,b){if("1"!=$(a).attr("calced")){var c=$(a).attr("fields").split(" "),d=null,e=null,f=null;Ext.each(c,function(a,c){var d=$("#"+b).find("[name="+this+"]")[0];
$(d).is("input.sum")&&"1"!=$(d).attr("calced")&&Calc.calcSumField(d,b);$(d).is("input.diff")&&"1"!=$(d).attr("calced")&&Calc.calcDiffField(d,b);$(d).is("input.multi")&&"1"!=$(d).attr("calced")&&Calc.calcMultiField(d,b);d=$("#"+b).find("[name="+this+"]").val();if("undefined"==typeof d||""==d.trim()||isNaN(parseFloat(NumUtil.removeComma(d),10)))return!0;0==c&&(e=Math.floor(parseFloat(NumUtil.removeComma(d),10)));1==c&&(f=Math.floor(parseFloat(NumUtil.removeComma(d),10)))});null==e&&null==f||(null==
e&&(e=0),null==f&&(f=0),d=e-f);null==d?$(a).val(""):$(a).val(NumUtil.addComma(""+Math.floor(d)));$(a).attr("calced","1")}},calcDiff:function(a){$("#"+a).find("input.diff").each(function(){Calc.calcDiffField(this,a)})},calcMultiField:function(a,b){if("1"!=$(a).attr("calced")){var c=$(a).attr("fields").split(" "),d=null;Ext.each(c,function(){var a=$("#"+b).find("[name="+this+"]")[0];$(a).is("input.sum")&&"1"!=$(a).attr("calced")&&Calc.calcSumField(a,b);$(a).is("input.diff")&&"1"!=$(a).attr("calced")&&
Calc.calcDiffField(a,b);$(a).is("input.multi")&&"1"!=$(a).attr("calced")&&Calc.calcMultiField(a,b);a=$(a).val();if("undefined"==typeof a||""==a.trim()||isNaN(parseFloat(NumUtil.removeComma(a),10)))return d=null,!1;null==d&&(d=1);d*=parseFloat(NumUtil.removeComma(a),10)});null==d?$(a).val(""):(c=$(a).attr("number"),"undefined"!=typeof c&&null!=c&&""!=c.trim()&&(isNaN(parseFloat(c))||(d=Math.floor(d*parseFloat(c)))),$(a).val(NumUtil.addComma(""+Math.floor(d))));$(a).attr("calced","1")}},calcMulti:function(a){$("#"+
a).find("input.multi").each(function(){Calc.calcMultiField(this,a)})}};FieldConvert={bindMasterReferenceChangeEvent:function(a){$("#"+a).find(":input.master_reference").each(function(){$(this).attr("master_code");var b=$(this).attr("data_key_field");$("#"+a).find(":input[name='"+b+"']").change(function(){FieldConvert.masterReferenceAll(a)})})},bindUserSelectButtonEvent:function(a){$("#"+a).find(":input[type='button'].user_select_button").live("click",function(){var b=$(this).attr("process_number");
UserSelectWindow.showWindow(b,a)});"template_body_new_doc"==a&&$("#"+a).find(":input[type='button'].user_select_button").each(function(){null!=$(this).attr("ok_to_show_process_number")&&$(this).hide()})},bindClearApproverButtonEvent:function(a){$("#"+a).find(":input[type='button'].clear_approver_button").live("click",function(){var b=$(this).attr("process_number"),b=$("#"+a).find(":input[name='process'][number='"+b+"']");ApproverCandidate.setNewApprovers(b,[],a)});"template_body_new_doc"==a&&$("#"+
a).find(":input[type='button'].clear_approver_button").each(function(){null!=$(this).attr("ok_to_show_process_number")&&$(this).hide()})},bindMasterSelectButtonEvent:function(a,b){$("#"+a).find(":input[type='button'].sateraito_master_select").live("click",function(){MasterWindow.masterSelectFormButtonClick(this,b)})},bindSateraitoAddressPopupButtonEvent:function(a){$("#"+a).find(":input[type='button'].sateraito_address_popup").live("click",function(){var b=$(this).attr("set_to_field");"undefined"==
typeof b||(null==b||""==b)||(b=$("#"+a).find(":input[name='"+b+"']").get(),null!=b&&0<b.length&&KozukasanPopup.sateraitoShowPopup2ByElement(b[0]))})},bindEventToGoogleCalendarButtonEvent:function(a,b){var c=function(d,c){var f=$(c).attr("data_fields").split(";"),g={};Ext.each(f,function(){var a=(""+this).split(":");g[a[0]]=a[1]});var f="",j=null,h=null,l=!1,m=!1;"undefined"!=typeof g.from&&""!=g.from&&$("#"+a).find(":input[name='"+g.from+"']").each(function(){var a=$(this).val(),b=new DateFormat("yyyy-MM-dd");
j=b.parse(a);null==j&&(b=new DateFormat("yyyy-MM-dd HH:mm:ss"),j=b.parse(a),l=!0)});"undefined"!=typeof g.to&&""!=g.to&&$("#"+a).find(":input[name='"+g.to+"']").each(function(){var a=$(this).val(),b=new DateFormat("yyyy-MM-dd");h=b.parse(a);null==h&&(b=new DateFormat("yyyy-MM-dd HH:mm:ss"),h=b.parse(a),m=!0)});null!=j&&l&&(j=new Date(j.getUTCFullYear(),j.getUTCMonth(),j.getUTCDate(),j.getUTCHours(),j.getUTCMinutes(),j.getUTCSeconds()));null!=h&&(m?h=new Date(h.getUTCFullYear(),h.getUTCMonth(),h.getUTCDate(),
h.getUTCHours(),h.getUTCMinutes(),h.getUTCSeconds()):h.setTime(h.getTime()+864E5));null==j&&null!=h?m?(j=new Date,j.setTime(h.getTime()-36E5)):j=h:null!=j&&null==h&&(l?(h=new Date,h.setTime(j.getTime()+36E5)):h=j);if(null!=j&&null!=h){var k;l&&m?(f=""+j.getFullYear()+("0"+(j.getMonth()+1)).slice(-2)+("0"+j.getDate()).slice(-2)+"T"+("0"+j.getHours()).slice(-2)+("0"+j.getMinutes()).slice(-2)+("0"+j.getSeconds()).slice(-2)+"Z",k=""+h.getFullYear()+("0"+(h.getMonth()+1)).slice(-2)+("0"+h.getDate()).slice(-2)+
"T"+("0"+h.getHours()).slice(-2)+("0"+h.getMinutes()).slice(-2)+("0"+h.getSeconds()).slice(-2)+"Z"):(f=""+j.getFullYear()+("0"+(j.getMonth()+1)).slice(-2)+("0"+j.getDate()).slice(-2),k=""+h.getFullYear()+("0"+(h.getMonth()+1)).slice(-2)+("0"+h.getDate()).slice(-2));f=f+"/"+k}else f="";var n="";"undefined"!=typeof g.title&&""!=g.title&&("doc_title"==g.title?n=$("#"+a).find(":input[name='doc_title_"+b+"']").val():$("#"+a).find(":input[name='"+g.title+"']").each(function(){n=$(this).val()}));var p="";
"undefined"!=typeof g.details&&""!=g.details&&$("#"+a).find(":input[name='"+g.details+"']").each(function(){p=$(this).val()});var q="";"undefined"!=typeof g.location&&""!=g.location&&$("#"+a).find(":input[name='"+g.location+"']").each(function(){q=$(this).val()});k="https://www.google.com/calendar/event?action=TEMPLATE&trp=false";""!=n&&(k=k+"&text="+encodeURIComponent(n));""!=f&&(k=k+"&dates="+encodeURIComponent(f));""!=p&&(k=k+"&details="+encodeURIComponent(p));""!=q&&(k=k+"&location="+encodeURIComponent(q));
window.open(k)};$("#"+a).find("input[type='button'].add_to_google_calendar").each(function(){var a=this;$(a).attr("src",SATERAITO_MY_SITE_URL+"/images/calendar_plus_ja.gif");$(a).live("click",function(){c("button",a)})});$("#"+a).find("img.add_to_google_calendar").each(function(){var a=this;$(a).attr("src",SATERAITO_MY_SITE_URL+"/images/calendar_plus_ja.gif");$(a).css("cursor","pointer");$(a).live("click",function(){c("img",a)})})},bindClearButtonEvent:function(a){$("#"+a).find("input[type='button'].clear_button").live("click",
function(){var b=$(this).attr("fields").split(" ");Ext.each(b,function(){var b=""+this;$("#"+a).find(":input[name='"+b+"']").val("")})})},convertDocCategoryCode:function(a,b,c,d,e){"undefined"==typeof b&&(b=!1);"undefined"==typeof d&&(d=!1);"undefined"==typeof e&&(e=!1);var f=$("#"+a).find(":input[name='doc_category_code']");if(0!=f.length){$("#"+a).find("#doc_category_name_render_area_"+a).remove();var g;g=""+('<span id="doc_category_name_render_area_'+a+'"></span>');b&&(g=g+'<button type="button" onclick="'+
("var docCategoryCode = $('#"+a+"').find(':input[name=doc_category_code]').val();"),g+="CategorySelectWindow.showWindow('"+a+"', docCategoryCode",d&&(g+=",true"),g+=");",g+='">'+MyLang.getMsg("MSG_SELECT_SOMETHING").replace(/%1/g,OtherSetting.wordingForCategory)+"</button>");e&&(g+='<button type="button" onclick="',g+="CategorySelectWindow.clearCategory('"+a+"');",g+='">'+MyLang.getMsg("CLEAR")+"</button>");$(f).after(g);"undefined"==typeof c||null==c?(b=$(f).val(),""==b?$("#doc_category_name_render_area_"+
a).text(""):DocCategory.requestDocCategory(b,!1,!0,function(b){b=b.category;$("#doc_category_name_render_area_"+a).text(b.category_name)})):$("#doc_category_name_render_area_"+a).text(c)}},convertDocTypeCodes:function(a,b,c){"undefined"==typeof b&&(b=!1);var d=$("#"+a).find(":input[name='doc_type_codes']");if(0!=d.length){$("#"+a).find("#doc_type_names_render_area_"+a).remove();var e=$(d).val().split(" "),f;f=""+('<span id="doc_type_names_render_area_'+a+'"></span>');b&&(f=f+('<button type="button" template_body_id="'+
a+'" onclick="FieldConvert.onSelectDocTypeClick(this);">')+MyLang.getMsg("MSG_SELECT_SOMETHING").replace(/%1/g,OtherSetting.wordingForDocType),f+="</button>");$(d).after(f);"undefined"==typeof c?DocType.requestDocTypeList(function(){var b="";Ext.each(e,function(){b+=" "+DocType.getDocTypeName(""+this)});$("#doc_type_names_render_area_"+a).text(b)},!0):$("#doc_type_names_render_area_"+a).text(c)}},dateFieldConvertAll:function(a,b){$("#"+a).find("input.date").each(function(){FieldConvert.dateFieldConvertEach(a,
b,this)})},dateFieldConvertEach:function(a,b,c){var d=$(c).attr("class"),e=$(c).attr("type");"undefined"==typeof e&&(e="text");if("text"==e||""==e){var e=$(c).attr("name"),f=$(c).val();if("undefined"==typeof f||null==f)f="";var g=!1;$(c).attr("disabled")&&(g=!0);var j=!1;$(c).attr("readonly")&&(j=!0);var h=$(c).attr("mandatory_msg");if("undefined"==typeof h||null==h)h="";var l=$(c).attr("list_key");if("undefined"==typeof l||null==l)l="";var m=$(c).attr("disp");if("undefined"==typeof m||null==m)m=
"";var k=$(c).attr("set_to_doc_title_order_number");$(c).after('<div style="display:inline-block;" id="date_field_render_area_'+a+"_"+e+'"></div>');f=new Ext.form.DateField({id:a+"_"+e,name:e,invalidText:MyLang.getMsg("VC_INVALID_DATE_FORMAT"),renderTo:"date_field_render_area_"+a+"_"+e,readOnly:j,disabled:g,value:f,format:"Y-m-d"});b.add(f);$("#date_field_render_area_"+a+"_"+e).find(":input[name='"+e+"']").addClass(d).attr("mandatory_msg",h).attr("list_key",l).attr("disp",m);"undefined"==typeof k||
null==k||$("#date_field_render_area_"+a+"_"+e).find(":input[name='"+e+"']").attr("set_to_doc_title_order_number",k);$(c).remove()}},getNumSetToDocTitleElement:function(){return $("#template_body_new_doc").find(":input.set_to_doc_title").size()},doSetToDocTitle:function(){var a=!1,b=[];$("#template_body_new_doc").find(":input.set_to_doc_title").each(function(){var c=$(this).attr("set_to_doc_title_order_number"),e=1E3;"undefined"==typeof c||(null==c||""==c||isNaN(c))||(e=parseInt(c,10));c=$(this).is(":input[type=checkbox]")?
$(this).is(":checked")?""+$(this).val():"":""+$(this).val();b.push({order_number:e,value:c});a=!0});if(a){b.sort(function(a,b){var c=a.order_number,g=b.order_number;return c<g?-1:c>g?1:0});var c="";Ext.each(b,function(){c+=""+this.value});Ext.getCmp("doc_title_new_doc").setValue(c)}},fillDataToMasterList:function(a){var b=[];$("#"+a).find("select.master_list").each(function(){var a=$(this).attr("master_code");-1==b.indexOf(a)&&b.push(a)});Ext.each(b,function(){var b=""+this;MasterData.requestMasterData(b,
!0,!1,function(d){$("#"+a).find("select.master_list[master_code='"+b+"']").each(function(){var a=this;Ext.each(d,function(){var b=this.data_key,c=this.attribute_1;$(a).append('<option value="'+b+'">'+Sateraito.Util.escapeHtml(c))})});$("#"+a).find("select.master_list[master_code='"+b+"']").removeClass("master_list");"template_body_new_doc"==a&&($("#template_body_to_submit").find("select.master_list[master_code='"+b+"']").each(function(){var a=this;Ext.each(d,function(){var b=this.data_key,c=this.attribute_1;
$(a).append('<option value="'+b+'">'+Sateraito.Util.escapeHtml(c))})}),$("#template_body_to_submit").find("select.master_list[master_code='"+b+"']").removeClass("master_list"))})})},masterReferenceAll:function(a){$("#"+a).find(":input.master_reference").each(function(){var b=this,c=$(b).attr("master_code"),d=$(b).attr("data_key_field"),d=$("#"+a).find(":input[name='"+d+"']").val(),e=$(b).attr("master_attribute");MasterData.requestMasterDataRow(c,d,function(a){"undefined"==typeof a[e]?$(b).val(""):
$(b).val(a[e])})})},numberFieldConvert:function(a,b){$("#"+a).find(":input.number").each(function(){FieldConvert._numberFieldConvert(a,b,this)})},_numberFieldConvert:function(a,b,c){var d=$(c).attr("class"),e=$(c).attr("type");"undefined"==typeof e&&(e="text");if("text"==e||""==e){var e=$(c).attr("name"),f=$(c).val();if("undefined"==typeof f||null==f)f="";var g=!1;$(c).attr("readonly")&&(g=!0);var j=!1;$(c).attr("disabled")&&(j=!0);var h=$(c).attr("fields");if("undefined"==typeof h||null==h)h="";
var l=$(c).attr("mandatory_msg");if("undefined"==typeof l||null==l)l="";var m=$(c).attr("list_key");if("undefined"==typeof m||null==m)m="";var k=$(c).attr("disp");if("undefined"==typeof k||null==k)k="";var n=$(c).width();$(c).after('<div style="display:inline-block;" id="number_field_render_area_'+a+"_"+e+'"></div>');f=new Ext.form.TextField({id:a+"_"+e,maskRe:/[0-9,-]/,name:e,invalidText:MyLang.getMsg("VC_INVALID_NUMERIC_FORMAT"),renderTo:"number_field_render_area_"+a+"_"+e,width:n,value:f,readOnly:g,
disabled:j,validator:function(a){a=NumUtil.removeComma(a);return isNaN(a)?MyLang.getMsg("VC_INVALID_NUMERIC_FORMAT2"):!0},listeners:{focus:function(a){var b=NumUtil.removeComma(a.getRawValue());a.setRawValue(b)},change:function(a){var b=NumUtil.removeComma(a.getRawValue());isNaN(b)||(b=NumUtil.addComma(b),a.setRawValue(b))}}});b.add(f);$("#number_field_render_area_"+a+"_"+e).find("input[name='"+e+"']").addClass(d).attr("fields",h).attr("list_key",m).attr("disp",k).attr("mandatory_msg",l);$(c).remove()}},
onSelectDocTypeClick:function(a){a=$(a).attr("template_body_id");var b=$("#"+a).find(":input[name='doc_type_codes']"),b=$(b).val();DocTypeSelectWindow.showWindow(a,b)},richTextFieldConvert:function(a,b){$("#"+a).find("textarea.richtext").each(function(){FieldConvert._richTextFieldConvert(a,b,this)})},_richTextFieldConvert:function(a,b,c){var d=$(c).attr("name"),e=$(c).val();WorkflowUser.requestToken(function(f){var g=f.token;$("body").append('<div id="dummy_for_inline_img" style="display:none;">'+
e+"</div>");Ext.each(b,function(){var a=this.new_file_id,b=this.original_file_id;$("#dummy_for_inline_img").find("img.inline_img[file_id='"+b+"']").each(function(){$(this).attr("file_id",a)});$("#dummy_for_inline_img").find(".download_attached_file[file_id='"+b+"']").each(function(){$(this).attr("file_id",a)})});$("#dummy_for_inline_img").find("img.inline_img").each(function(){var a=$(this).attr("file_id");null==a||""==a||$(this).attr("src",SATERAITO_MY_SITE_URL+"/"+SATERAITO_GOOGLE_APPS_DOMAIN+"/"+
LoginMgr.appId+"/attach/downloadattachedfile?file_id="+encodeURIComponent(a)+"&token="+encodeURIComponent(g)+"&screen="+LoginMgr.screenName)});e=$("#dummy_for_inline_img").html();$("#dummy_for_inline_img").remove();$(c).after('<div id="richtext_field_render_area_'+a+"_"+d+'"></div>');var j=new Ext.form.HtmlEditor({renderTo:"richtext_field_render_area_"+a+"_"+d,id:"richtext_field_"+a+"_"+d,name:d,fontFamilies:"Arial;Courier New;Tahoma;Times New Roman;Verdana;\uff2d\uff33 \uff30\u30b4\u30b7\u30c3\u30af;\uff2d\uff33 \uff30\u660e\u671d;\uff2d\uff33 \u30b4\u30b7\u30c3\u30af;\uff2d\uff33 \u660e\u671d".split(";"),
defaultFont:"Arial",cls:"richtext",width:$(c).width(),height:$(c).height(),listeners:{initialize:function(a){if(a=a.getEditorBody())a.style.fontFamily="Arial"}}});(function(){j.setValue(e)}).defer(500);$(c).remove()})},setSubmitterInfo:function(a){$("#template_body_new_doc").find(":input.viewer_name").val(DisplayMgr.formatUserName(a.family_name,a.given_name));$("#template_body_new_doc").find(":input.job_title").val(a.job_title);$("#template_body_new_doc").find(":input.department_1").val(a.department_1);
$("#template_body_new_doc").find(":input.department_2").val(a.department_2);$("#template_body_new_doc").find(":input.department_3").val(a.department_3);$("#template_body_new_doc").find(":input.employee_id").val(a.employee_id);for(var b=1;5>=b;b++)$("#template_body_new_doc").find(":input.user_attribute_"+b).each(function(){var c=""+a["user_attribute_"+b];if("first_value"==$(this).attr("option")){var d=c.split(" ");0<d.length?$(this).val(d[0]):$(this).val(c)}else $(this).val(c);d=$(this).attr("set_full_value_to");
if(!("undefined"==typeof d||null==d||""==d)){var e=d.split(":"),d=e[0],e=e[1];$("#template_body_new_doc").find(":input[name='"+d+"']").attr(e,c)}})},setValIfGhostWriter:function(a){$("#template_body_new_doc").find(":input.set_val_if_ghost_writer").each(function(){var b;b=""==a?$(this).attr("author_val"):$(this).attr("ghost_writer_val");"undefined"==typeof b||null==b||$(this).val(b)})}};MyUtil={isValidAppId:function(a){return!/^[a-zA-Z][a-zA-Z0-9_-]+$/.test(a)||1<a.split("_____").length?!1:!0}};DocDetailWindow=
{init:function(a){var b=[];$("#template_body_"+a).find("*").each(function(){var a=$(this).attr("name");"undefined"==typeof a||(null==a||""==a)||"process"!=a.toLowerCase()&&b.push(a)});DocDetailWindow.showInputFields(b,a)},showInputFields:function(a,b){var c=Ext.getCmp("form_panel_"+b).getForm();Ext.each(a,function(){var a=""+this,e=$("#"+b).find(":input[name="+a+"]");$(e).attr("name");var f=$(e).attr("type");"undefined"==typeof f&&(f="text");f=f.toLowerCase();$(e).is("textarea")&&($("#"+b).find("span.sateraito_doc_value[name="+
a+"]").hide(),$(e).show(),$(e).removeAttr("disabled"),$(e).hasClass("richtext")&&FieldConvert._richTextFieldConvert(b,e));"checkbox"==f&&$(e).removeAttr("disabled");$(e).is("input")&&"text"==f&&($("#"+b).find("span.sateraito_doc_value[name="+a+"]").hide(),$(e).show(),$(e).removeAttr("disabled"),$(e).hasClass("number")&&FieldConvert._numberFieldConvert(b,c,e),$(e).hasClass("date")&&FieldConvert.dateFieldConvertEach(b,c,e));"radio"==f&&$("#"+b).find(":input[name="+a+"]").removeAttr("disabled");$(e).is("select")&&
$(e).removeAttr("disabled");"button"==f&&$(e).is(".clear_button")&&$(e).show()});$("#"+b).find(":input").change(function(){Calc.calcAll(b)});FieldConvert.bindClearButtonEvent(b)}}})();
