/*
 jQuery blockUI plugin
 Version 2.70.0-2014.11.23
 Requires jQuery v1.7 or later

 Examples at: http://malsup.com/jquery/block/
 Copyright (c) 2007-2013 M. Alsup
 Dual licensed under the MIT and GPL licenses:
 http://www.opensource.org/licenses/mit-license.php
 http://www.gnu.org/licenses/gpl.html

 Thanks to Amir-Hossein Sobhi for some excellent contributions!
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(d,b,l){d instanceof String&&(d=String(d));for(var m=d.length,h=0;h<m;h++){var r=d[h];if(b.call(l,r,h,d))return{i:h,v:r}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(d,b,l){d!=Array.prototype&&d!=Object.prototype&&(d[b]=l.value)};
$jscomp.getGlobal=function(d){return"undefined"!=typeof window&&window===d?d:"undefined"!=typeof global&&null!=global?global:d};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(d,b,l,m){if(b){l=$jscomp.global;d=d.split(".");for(m=0;m<d.length-1;m++){var h=d[m];h in l||(l[h]={});l=l[h]}d=d[d.length-1];m=l[d];b=b(m);b!=m&&null!=b&&$jscomp.defineProperty(l,d,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("Array.prototype.find",function(d){return d?d:function(b,d){return $jscomp.findInternal(this,b,d).v}},"es6","es3");
(function(){function d(b){function d(c,a){var g=c==window,e=a&&void 0!==a.message?a.message:void 0;a=b.extend({},b.blockUI.defaults,a||{});if(!a.ignoreIfBlocked||!b(c).data("blockUI.isBlocked")){a.overlayCSS=b.extend({},b.blockUI.defaults.overlayCSS,a.overlayCSS||{});var d=b.extend({},b.blockUI.defaults.css,a.css||{});a.onOverlayClick&&(a.overlayCSS.cursor="pointer");var n=b.extend({},b.blockUI.defaults.themedCSS,a.themedCSS||{});e=void 0===e?a.message:e;g&&p&&m(window,{fadeOut:0});if(e&&"string"!=
typeof e&&(e.parentNode||e.jquery)){var k=e.jquery?e[0]:e,f={};b(c).data("blockUI.history",f);f.el=k;f.parent=k.parentNode;f.display=k.style.display;f.position=k.style.position;f.parent&&f.parent.removeChild(k)}b(c).data("blockUI.onUnblock",a.onUnblock);f=a.baseZ;var h=u||a.forceIframe?b('<iframe class="blockUI" style="z-index:'+f++ +';display:none;border:none;margin:0;padding:0;position:absolute;width:100%;height:100%;top:0;left:0" src="'+a.iframeSrc+'"></iframe>'):b('<div class="blockUI" style="display:none"></div>');
k=a.theme?b('<div class="blockUI blockOverlay ui-widget-overlay" style="z-index:'+f++ +';display:none"></div>'):b('<div class="blockUI blockOverlay" style="z-index:'+f++ +';display:none;border:none;margin:0;padding:0;width:100%;height:100%;top:0;left:0"></div>');a.theme&&g?(f='<div class="blockUI '+a.blockMsgClass+' blockPage ui-dialog ui-widget ui-corner-all" style="z-index:'+(f+10)+';display:none;position:fixed">',a.title&&(f+='<div class="ui-widget-header ui-dialog-titlebar ui-corner-all blockTitle">'+
(a.title||"&nbsp;")+"</div>"),f+='<div class="ui-widget-content ui-dialog-content"></div></div>'):a.theme?(f='<div class="blockUI '+a.blockMsgClass+' blockElement ui-dialog ui-widget ui-corner-all" style="z-index:'+(f+10)+';display:none;position:absolute">',a.title&&(f+='<div class="ui-widget-header ui-dialog-titlebar ui-corner-all blockTitle">'+(a.title||"&nbsp;")+"</div>"),f+='<div class="ui-widget-content ui-dialog-content"></div></div>'):f=g?'<div class="blockUI '+a.blockMsgClass+' blockPage" style="z-index:'+
(f+10)+';display:none;position:fixed"></div>':'<div class="blockUI '+a.blockMsgClass+' blockElement" style="z-index:'+(f+10)+';display:none;position:absolute"></div>';f=b(f);e&&(a.theme?(f.css(n),f.addClass("ui-widget-content")):f.css(d));a.theme||k.css(a.overlayCSS);k.css("position",g?"fixed":"absolute");(u||a.forceIframe)&&h.css("opacity",0);d=[h,k,f];var l=g?b("body"):b(c);b.each(d,function(){this.appendTo(l)});a.theme&&a.draggable&&b.fn.draggable&&f.draggable({handle:".ui-dialog-titlebar",cancel:"li"});
n=B&&(!b.support.boxModel||0<b("object,embed",g?null:c).length);if(x||n){g&&a.allowBodyStretch&&b.support.boxModel&&b("html,body").css("height","100%");if((x||!b.support.boxModel)&&!g){n=parseInt(b.css(c,"borderTopWidth"),10)||0;var t=parseInt(b.css(c,"borderLeftWidth"),10)||0,y=n?"(0 - "+n+")":0,z=t?"(0 - "+t+")":0}b.each(d,function(b,c){c=c[0].style;c.position="absolute";2>b?(g?c.setExpression("height","Math.max(document.body.scrollHeight, document.body.offsetHeight) - (jQuery.support.boxModel?0:"+
a.quirksmodeOffsetHack+') + "px"'):c.setExpression("height",'this.parentNode.offsetHeight + "px"'),g?c.setExpression("width",'jQuery.support.boxModel && document.documentElement.clientWidth || document.body.clientWidth + "px"'):c.setExpression("width",'this.parentNode.offsetWidth + "px"'),z&&c.setExpression("left",z),y&&c.setExpression("top",y)):a.centerY?(g&&c.setExpression("top",'(document.documentElement.clientHeight || document.body.clientHeight) / 2 - (this.offsetHeight / 2) + (blah = document.documentElement.scrollTop ? document.documentElement.scrollTop : document.body.scrollTop) + "px"'),
c.marginTop=0):!a.centerY&&g&&(b=a.css&&a.css.top?parseInt(a.css.top,10):0,c.setExpression("top","((document.documentElement.scrollTop ? document.documentElement.scrollTop : document.body.scrollTop) + "+b+') + "px"'))})}e&&(a.theme?f.find(".ui-widget-content").append(e):f.append(e),(e.jquery||e.nodeType)&&b(e).show());(u||a.forceIframe)&&a.showOverlay&&h.show();a.fadeIn?(d=a.onBlock?a.onBlock:v,h=a.showOverlay&&!e?d:v,d=e?d:v,a.showOverlay&&k._fadeIn(a.fadeIn,h),e&&f._fadeIn(a.fadeIn,d)):(a.showOverlay&&
k.show(),e&&f.show(),a.onBlock&&a.onBlock.bind(f)());r(1,c,a);g?(p=f[0],q=b(a.focusableElements,p),a.focusInput&&setTimeout(A,20)):C(f[0],a.centerX,a.centerY);a.timeout&&(e=setTimeout(function(){g?b.unblockUI(a):b(c).unblock(a)},a.timeout),b(c).data("blockUI.timeout",e))}}function m(c,a){var d=c==window,e=b(c),w=e.data("blockUI.history"),n=e.data("blockUI.timeout");n&&(clearTimeout(n),e.removeData("blockUI.timeout"));a=b.extend({},b.blockUI.defaults,a||{});r(0,c,a);null===a.onUnblock&&(a.onUnblock=
e.data("blockUI.onUnblock"),e.removeData("blockUI.onUnblock"));var k=d?b("body").children().filter(".blockUI").add("body > .blockUI"):e.find(">.blockUI");a.cursorReset&&(1<k.length&&(k[1].style.cursor=a.cursorReset),2<k.length&&(k[2].style.cursor=a.cursorReset));d&&(p=q=null);if(a.fadeOut){var f=k.length;k.stop().fadeOut(a.fadeOut,function(){0===--f&&h(k,w,a,c)})}else h(k,w,a,c)}function h(c,a,d,e){var g=b(e);if(!g.data("blockUI.isBlocked")){c.each(function(a,b){this.parentNode&&this.parentNode.removeChild(this)});
a&&a.el&&(a.el.style.display=a.display,a.el.style.position=a.position,a.el.style.cursor="default",a.parent&&a.parent.appendChild(a.el),g.removeData("blockUI.history"));g.data("blockUI.static")&&g.css("position","static");if("function"==typeof d.onUnblock)d.onUnblock(e,d);c=b(document.body);a=c.width();d=c[0].style.width;c.width(a-1).width(a);c[0].style.width=d}}function r(c,a,d){var e=a==window;a=b(a);if(c||(!e||p)&&(e||a.data("blockUI.isBlocked")))a.data("blockUI.isBlocked",c),e&&d.bindEvents&&(!c||
d.showOverlay)&&(c?b(document).bind("mousedown mouseup keydown keypress keyup touchstart touchend touchmove",d,t):b(document).unbind("mousedown mouseup keydown keypress keyup touchstart touchend touchmove",t))}function t(c){if("keydown"===c.type&&c.keyCode&&9==c.keyCode&&p&&c.data.constrainTabKey){var a=q,d=c.shiftKey&&c.target===a[0];if(!c.shiftKey&&c.target===a[a.length-1]||d)return setTimeout(function(){A(d)},10),!1}a=c.data;var e=b(c.target);if(e.hasClass("blockOverlay")&&a.onOverlayClick)a.onOverlayClick(c);
return 0<e.parents("div."+a.blockMsgClass).length?!0:0===e.parents().children().filter("div.blockUI").length}function A(b){q&&(b=q[!0===b?q.length-1:0])&&b.focus()}function C(c,a,d){var e=c.parentNode,g=c.style,h=(e.offsetWidth-c.offsetWidth)/2-(parseInt(b.css(e,"borderLeftWidth"),10)||0);c=(e.offsetHeight-c.offsetHeight)/2-(parseInt(b.css(e,"borderTopWidth"),10)||0);a&&(g.left=0<h?h+"px":"0");d&&(g.top=0<c?c+"px":"0")}b.fn._fadeIn=b.fn.fadeIn;var v=b.noop||function(){},u=/MSIE/.test(navigator.userAgent),
x=/MSIE 6.0/.test(navigator.userAgent)&&!/MSIE 8.0/.test(navigator.userAgent),B=b.isFunction(document.createElement("div").style.setExpression);b.blockUI=function(b){d(window,b)};b.unblockUI=function(b){m(window,b)};b.growlUI=function(c,a,d,e){var g=b('<div class="growlUI"></div>');c&&g.append("<h1>"+c+"</h1>");a&&g.append("<h2>"+a+"</h2>");void 0===d&&(d=3E3);var h=function(a){a=a||{};b.blockUI({message:g,fadeIn:"undefined"!==typeof a.fadeIn?a.fadeIn:700,fadeOut:"undefined"!==typeof a.fadeOut?a.fadeOut:
1E3,timeout:"undefined"!==typeof a.timeout?a.timeout:d,centerY:!1,showOverlay:!1,onUnblock:e,css:b.blockUI.defaults.growlCSS})};h();g.css("opacity");g.mouseover(function(){h({fadeIn:0,timeout:3E4});var a=b(".blockMsg");a.stop();a.fadeTo(300,1)}).mouseout(function(){b(".blockMsg").fadeOut(1E3)})};b.fn.block=function(c){if(this[0]===window)return b.blockUI(c),this;var a=b.extend({},b.blockUI.defaults,c||{});this.each(function(){var c=b(this);a.ignoreIfBlocked&&c.data("blockUI.isBlocked")||c.unblock({fadeOut:0})});
return this.each(function(){"static"==b.css(this,"position")&&(this.style.position="relative",b(this).data("blockUI.static",!0));this.style.zoom=1;d(this,c)})};b.fn.unblock=function(c){return this[0]===window?(b.unblockUI(c),this):this.each(function(){m(this,c)})};b.blockUI.version=2.7;b.blockUI.defaults={message:"<h1>Please wait...</h1>",title:null,draggable:!0,theme:!1,css:{padding:0,margin:0,width:"30%",top:"40%",left:"35%",textAlign:"center",color:"#000",border:"3px solid #aaa",backgroundColor:"#fff",
cursor:"wait"},themedCSS:{width:"30%",top:"40%",left:"35%"},overlayCSS:{backgroundColor:"#000",opacity:.6,cursor:"wait"},cursorReset:"default",growlCSS:{width:"350px",top:"10px",left:"",right:"10px",border:"none",padding:"5px",opacity:.6,cursor:"default",color:"#fff",backgroundColor:"#000","-webkit-border-radius":"10px","-moz-border-radius":"10px","border-radius":"10px"},iframeSrc:/^https/i.test(window.location.href||"")?"javascript:false":"about:blank",forceIframe:!1,baseZ:1E3,centerX:!0,centerY:!0,
allowBodyStretch:!0,bindEvents:!0,constrainTabKey:!0,fadeIn:200,fadeOut:400,timeout:0,showOverlay:!0,focusInput:!0,focusableElements:":input:enabled:visible",onBlock:null,onUnblock:null,onOverlayClick:null,quirksmodeOffsetHack:4,blockMsgClass:"blockMsg",ignoreIfBlocked:!1};var p=null,q=[]}"function"===typeof define&&define.amd&&define.amd.jQuery?define(["jquery"],d):d(jQuery)})();
