(function(){Sateraito={GadgetHeight:{DEFAULT_GADGET_HEIGHT:200,getUserPrefs:function(a){var c=new gadgets.Prefs,c=parseInt(c.getString("gh"),10);isNaN(c)&&(c="undefined"==typeof a?Sateraito.GadgetHeight.DEFAULT_GADGET_HEIGHT:a);return c},setGadgetHeight:function(){(function(){gadgets&&gadgets.window&&gadgets.window.adjustHeight(Sateraito.GadgetHeight.getUserPrefs())}).defer(1E3)}},DateUtil:{dayOfWeek:"\u65e5\u6708\u706b\u6c34\u6728\u91d1\u571f".split(""),dayOfWeekEn:"Sun Mon Tue Wed Thu Fri Sat".split(" "),
getDateDiff:function(a,c){var b=a.split("-"),b=new Date(parseInt(b[0],10),parseInt(b[1],10)-1,parseInt(b[2],10)),d=c.split("-");return(new Date(parseInt(d[0],10),parseInt(d[1],10)-1,parseInt(d[2],10))-b)/864E5},getFutureDateStr:function(a,c){if("undefined"==typeof a)return null;var b=a.split("-"),b=new Date(parseInt(b[0],10),parseInt(b[1],10)-1,parseInt(b[2],10));b.setTime(b.getTime()+864E5*c);return Sateraito.DateUtil.myFormatDate(b)},timeShorten:function(a){if("undefined"==typeof a||""==a)return"";
a=a.split(":");return a[0]+":"+a[1]},datePart:function(a){return"undefined"==typeof a?"":a.split(" ")[0]},datetimeShorten:function(a){if("undefined"==typeof a||""==a)return"";a=a.split(":");return a[0]+":"+a[1]},shorten:function(a){a=a.split("-");return""+parseInt(a[1],10)+"/"+a[2]},checkDate:function(a,c,b){var d=new Date(a,c-1,b);return null==d||d.getFullYear()!=a||d.getMonth()+1!=c||d.getDate()!=b?!1:!0},myFormatDate:function(a){var c=a.getFullYear(),b=a.getMonth()+1;a=a.getDate();10>b&&(b="0"+
b);10>a&&(a="0"+a);return""+c+"-"+b+"-"+a},getTodayStr:function(){return Sateraito.DateUtil.myFormatDate(new Date)},formatNumToDate:function(a,c,b){return""+a+"-"+(10>c?"0"+c:""+c)+"-"+(10>b?"0"+b:""+b)},compareDate:function(a,c){var b=new Date(a),d=new Date(c),b=Date.UTC(b.getFullYear(),b.getMonth()+1,b.getDate()),d=Date.UTC(d.getFullYear(),d.getMonth()+1,d.getDate());return parseFloat(b)<parseFloat(d)?-1:parseFloat(b)==parseFloat(d)?0:parseFloat(b)>parseFloat(d)?1:null},operaterDayFromTwoDate:function(a,
c){var b=new Date(a),d=new Date(c),b=Date.UTC(b.getFullYear(),b.getMonth()+1,b.getDate()),d=Date.UTC(d.getFullYear(),d.getMonth()+1,d.getDate()),d=parseFloat(b)-parseFloat(d);return parseFloat(d/864E5)}},Lang:{getMsg:function(a){return gadgets&&gadgets.Prefs?(new gadgets.Prefs).getMsg(a):MyLang.getMsg(a)}},Util:{isSecurityBrowser:function(){return 0<=window.navigator.userAgent.indexOf("SateraitoSecurityBrowser")?!0:!1},console:function(a){"undefined"!=typeof window.console&&window.console.log(a)},
getUriParams:function(a){if(null==a||"undefined"==typeof a||""==a)return{};var c={};a=String(a).split("?");1<a.length&&(a=String(a[1]).split("&"),0<a.length&&Ext.each(a,function(){var a=String(this).split("=");1<a.length&&(c[a[0]]=a[1])}));return c},escapeHtml:function(a){return null==a?null:a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")},enterToBr:function(a){return null==a||"undefined"==typeof a?"":a.replace(/\n/g,"<br />")},isAllSingleByteChar:function(a){for(var c=
0;c<a.length;c++){var b=a.charAt(c);if(!(0<=" !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~".indexOf(b)))return!1}return!0},isAllSplitedValEmail:function(a){a=a.split(" ");var c=!1;Ext.each(a,function(a){if(!Sateraito.Util.isMailAddress(a))return c=!0,!1});return c?!1:!0},isMailAddress:function(a){a=a.split("@");return 2!=a.length||2>a[1].split(".").length?!1:!0},isSmartPhone:function(){var a=window.navigator.userAgent;return 0<=a.indexOf("iPhone")||
0<=a.indexOf("iPad")||0<=a.indexOf("iPod")||0<=a.indexOf("Android")?!0:!1},myBoolToNum:function(a){return a?1:0},boolToStr:function(a){return a.toString().toLowerCase()},myImplode:function(a,c){"undefined"==typeof c&&(c=",");var b="";Ext.each(a,function(a,e){""!=b&&(b+=c);b+=a});return b},requestParam:function(a,c,b){"undefined"==typeof a&&(a=!1);"undefined"==typeof b&&(b=0);var d={};d[gadgets.io.RequestParameters.CONTENT_TYPE]=gadgets.io.ContentType.JSON;d[gadgets.io.RequestParameters.AUTHORIZATION]=
gadgets.io.AuthorizationType.SIGNED;d[gadgets.io.RequestParameters.REFRESH_INTERVAL]=b;a?(d[gadgets.io.RequestParameters.METHOD]=gadgets.io.MethodType.POST,d[gadgets.io.RequestParameters.POST_DATA]=gadgets.io.encodeValues(c)):d[gadgets.io.RequestParameters.METHOD]=gadgets.io.MethodType.GET;return d},isShowLargePopup:function(a){return 0<=["c6c899f09cbbc972173f845afc054b56","1c0bdad114a9aaac31e91604540d0289"].indexOf(CryptoJS.MD5(a).toString())?!0:!1}},MiniMessage:{message:null,fontSize:12,initMessageArea:function(a){"undefined"!=
typeof a&&(Sateraito.MiniMessage.fontSize=a);a='<div id="mini_message" style="position:absolute; top:0px; left:0px; width:200px; text-align:center; z-index:10000;"></div>';$("body").append(a);a=$(window).width();var c=$("#mini_message").width();$("#mini_message").css("left",""+(a/2-c/2)+"px")},clearMessage:function(){if(null!=Sateraito.MiniMessage.message){var a=new gadgets.Prefs;(new gadgets.MiniMessage(a.getModuleId(),$("#mini_message")[0])).dismissMessage(Sateraito.MiniMessage.message);Sateraito.MiniMessage.message=
null}},showTimerMessage:function(a,c){"undefined"==typeof c&&(c=3);var b=new gadgets.Prefs;(new gadgets.MiniMessage(b.getModuleId(),$("#mini_message")[0])).createTimerMessage(a,c).style.fontSize=""+Sateraito.MiniMessage.fontSize+"px"},showLoadingMessage:function(a){var c=new gadgets.Prefs;"undefined"==typeof a&&(a=c.getMsg("LOADING"));Sateraito.MiniMessage.clearMessage();c=new gadgets.MiniMessage(c.getModuleId(),$("#mini_message")[0]);Sateraito.MiniMessage.message=c.createStaticMessage(a);Sateraito.MiniMessage.message.style.fontSize=
""+Sateraito.MiniMessage.fontSize+"px"}},EventController:{MAX_RETRY:10},GadgetSetting:{settingName:null,settingObj:{},mySiteUrl:null,init:function(a,c){Sateraito.GadgetSetting.settingName=a;Sateraito.GadgetSetting.mySiteUrl=c},requestGetGadgetSetting:function(a,c){"undefined"==typeof c&&(c=1);SimpleRequest.get({baseUrl:Sateraito.GadgetSetting.mySiteUrl,methodUrl:"/getgadgetsetting?setting_name="+Sateraito.GadgetSetting.settingName,callback:function(b){b.is_error?(Sateraito.Util.console(b.error_code),
a(null)):(Sateraito.GadgetSetting.settingObj=gadgets.json.parse(decodeURI(b.setting_value)),a(Sateraito.GadgetSetting.settingObj))}})},requestSetGadgetSetting:function(a,c,b){"undefined"==typeof b&&(b=1);a=encodeURI(gadgets.json.stringify(a));SimpleRequest.post({baseUrl:Sateraito.GadgetSetting.mySiteUrl,methodUrl:"/setgadgetsetting",postData:{setting_name:Sateraito.GadgetSetting.settingName,setting_value:a},callback:function(a){c()}})}},checkInitialized:function(a,c){var b=function(a){var b=SATERAITO_MY_SITE_URL+
"/"+SATERAITO_GOOGLE_APPS_DOMAIN+"/batch3",c="/autogetmyjoininggroup?email_to_check="+encodeURIComponent(VIEWER_EMAIL)+"&viewer_email="+encodeURIComponent(VIEWER_EMAIL);SimpleRequest.get({baseUrl:b,methodUrl:c,callback:a})},d=function(a){var b=SATERAITO_MY_SITE_URL+"/"+SATERAITO_GOOGLE_APPS_DOMAIN+"/batch3",c="/checkautogetmyjoininggroup?email_to_check="+encodeURIComponent(VIEWER_EMAIL)+"&viewer_email="+encodeURIComponent(VIEWER_EMAIL);SimpleRequest.get({baseUrl:b,methodUrl:c,callback:a})};if(a.google_apps_groups_new_user)if(a.google_apps_groups_first_process&&
""===a.google_apps_groups_state)$("#output").html('<p class="loading-dot" style="padding:10px 10px;font-size: 20px;">'+MyLang.getMsg("IS_INITIALIZING")+"</p>"),b(function(){var a=setInterval(function(){d(function(b){"FINISHED"===b.status&&(clearInterval(a),$("#output").html(""),c())})},5E3)});else if(a.google_apps_groups_first_process&&"PROCESSING"===a.google_apps_groups_state){$("#output").html('<p class="loading-dot" style="padding:10px 10px;font-size: 20px;">'+MyLang.getMsg("IS_INITIALIZING")+
"</p>");var e=setInterval(function(){d(function(a){"FINISHED"===a.status&&(clearInterval(e),$("#output").text(""),c())})},5E3)}else c();else c()}}})();
