var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,a,c){b!=Array.prototype&&b!=Object.prototype&&(b[a]=c.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var b=0;return function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+b++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.iterator;b||(b=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[b]&&$jscomp.defineProperty(Array.prototype,b,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.asyncIterator;b||(b=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.arrayIterator=function(b){var a=0;return $jscomp.iteratorPrototype(function(){return a<b.length?{done:!1,value:b[a++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(b){$jscomp.initSymbolIterator();b={next:b};b[$jscomp.global.Symbol.iterator]=function(){return this};return b};$jscomp.iteratorFromArray=function(b,a){$jscomp.initSymbolIterator();b instanceof String&&(b+="");var c=0,d={next:function(){if(c<b.length){var e=c++;return{value:a(e,b[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};
$jscomp.polyfill=function(b,a,c,d){if(a){c=$jscomp.global;b=b.split(".");for(d=0;d<b.length-1;d++){var e=b[d];e in c||(c[e]={});c=c[e]}b=b[b.length-1];d=c[b];a=a(d);a!=d&&null!=a&&$jscomp.defineProperty(c,b,{configurable:!0,writable:!0,value:a})}};$jscomp.polyfill("Array.prototype.keys",function(b){return b?b:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
Ext.ucf.file={RecordInfo:Ext.data.Record.create([{name:"unique_id",type:"string"},{name:"data_key",type:"string"},{name:"data_type",type:"string"},{name:"data_kind",type:"string"},{name:"data_name",type:"string"},{name:"data_path",type:"string"},{name:"data_size",type:"string"},{name:"access_url",type:"string"},{name:"blob_key",type:"string"},{name:"status",type:"string"},{name:"deal_status",type:"string"},{name:"upload_operator_id",type:"string"},{name:"upload_operator_unique_id",type:"string"},
{name:"last_upload_operator_id",type:"string"},{name:"last_upload_operator_unique_id",type:"string"},{name:"last_upload_date",type:"string"},{name:"upload_count",type:"string"},{name:"download_operator_id",type:"string"},{name:"download_operator_unique_id",type:"string"},{name:"last_download_operator_id",type:"string"},{name:"last_download_operator_unique_id",type:"string"},{name:"last_download_date",type:"string"},{name:"download_count",type:"string"},{name:"log_text",type:"string"},{name:"date_created",
type:"string"},{name:"date_changed",type:"string"},{name:"expire_date",type:"string"}]),dispLogTextDetail:function(b){var a=function(a){a=new Ext.FormPanel({labelWidth:30,frame:!1,width:900,layout:"fit",items:[{xtype:"fieldset",autoHeight:!0,autoWidth:!0,defaults:{width:600,height:400},defaultType:"textarea",items:[{fieldLabel:"",name:"log_text",value:a,readOnly:!0}]}],buttons:[{text:_msg.VMSG_CLOSE,handler:function(){b.close()}}]});var b=new Ext.Window({title:_msg.LOG,layout:"fit",modal:!0,width:700,
height:500,plain:!0,autoDestory:!0,items:a});b.show();b.dd.constrainTo(Ext.getBody())},c=function(b){void 0!=b.responseText&&""!=b.responseText&&(b=jQuery.parseJSON(b.responseText),0==b.code&&a(b.log_text))};Ext.Ajax.request({url:_vurl+"file/xtgetdetail",method:"POST",params:{unique_id:b},success:c,failure:c})},viewHelper:function(){return{vh_basic:function(b,a,c){return""+Ext.ucf.htmlEscape(b)},vh_download_operator_id:function(b,a,c){a="";return a=(operator_unique_id=c.get("download_operator_unique_id"))&&
""!=operator_unique_id?a+('<a href="'+_vurl+"account/detail?unqid="+escape(operator_unique_id)+'&tp=r" >'+Ext.ucf.htmlEscape(b)+"</a>"):a+Ext.ucf.htmlEscape(b)},vh_upload_operator_id:function(b,a,c){a="";return a=(operator_unique_id=c.get("upload_operator_unique_id"))&&""!=operator_unique_id?a+('<a href="'+_vurl+"account/detail?unqid="+escape(operator_unique_id)+'&tp=r" >'+Ext.ucf.htmlEscape(b)+"</a>"):a+Ext.ucf.htmlEscape(b)},vh_last_download_operator_id:function(b,a,c){a="";return a=(operator_unique_id=
c.get("last_download_operator_unique_id"))&&""!=operator_unique_id?a+('<a href="'+_vurl+"account/detail?unqid="+escape(operator_unique_id)+'&tp=r" >'+Ext.ucf.htmlEscape(b)+"</a>"):a+Ext.ucf.htmlEscape(b)},vh_last_upload_operator_id:function(b,a,c){a="";return a=(operator_unique_id=c.get("last_upload_operator_unique_id"))&&""!=operator_unique_id?a+('<a href="'+_vurl+"account/detail?unqid="+escape(operator_unique_id)+'&tp=r" >'+Ext.ucf.htmlEscape(b)+"</a>"):a+Ext.ucf.htmlEscape(b)},vh_data_name:function(b,
a,c){a="";return a=(data_key=c.get("data_key"))&&""!=data_key?a+('<a href="'+_vurl+"file/download?data_key="+escape(data_key)+'" >'+Ext.ucf.htmlEscape(b)+"</a>"):a+Ext.ucf.htmlEscape(b)},vh_status:function(b,a,c){a="";return a="FAILED"==b?a+Ext.ucf.htmlEscape(_msg.PROCESS_RESULT_FAILED):"SUCCESS"==b?a+Ext.ucf.htmlEscape(_msg.PROCESS_RESULT_SUCCESS):a+Ext.ucf.htmlEscape(b)},vh_deal_status:function(b,a,c){a="";return a="CREATING"==b?a+Ext.ucf.htmlEscape(_msg.PROCESS_RESULT_PROCESSING):"FIN"==b?a+Ext.ucf.htmlEscape(_msg.PROCESS_RESULT_FIN):
a+Ext.ucf.htmlEscape(b)},vh_log_text:function(b,a,c){b="";c.get("log_text")&&""!=c.get("log_text")&&(b+="<a href=\"JavaScript:Ext.ucf.file.dispLogTextDetail('"+c.get("unique_id")+"')\" >"+_msg.LOG+"</a>");return b}}},createExportHistoryGridPanel:function(b,a,c){a||(a={});a.panel_title||(a.panel_title=_msg.VMSG_EXPORT_HISTORY);a.export_button_title||(a.export_button_title=_msg.VMSG_EXPORT);a.without_operator_link||(a.without_operator_link=!1);a.without_export_button||(a.without_export_button=!1);var d=
new Ext.data.Store({reader:new Ext.data.JsonReader({idProperty:"unique_id",root:"records",totalProperty:"all_count"},Ext.ucf.file.RecordInfo),url:_vurl+"file/xtlist",autoDestroy:!0}),e=function(){return{start:0,limit:10,data_kind:b}},g=function(){Ext.ucf.search(!1,d,e,"")},f=new Ext.Button({iconCls:"reflesh",handler:g}),l=new Ext.PagingToolbar({pageSize:10,store:d,displayInfo:!0,displayMsg:_msg.PAGING_BAR,emptyMsg:_msg.NO_DISP_DATA,items:["->"]});f=[f];a.without_export_button||(f.push("-"),f.push({text:a.export_button_title,
handler:function(){Ext.ucf.exportToCsv({data_kind:b},a.mask_area)}}),f.push("-"));c&&0<c.length&&(f.push(c),f.push("-"));c=new Ext.Toolbar({items:f});f=new Ext.grid.ColumnModel({columns:[{header:_msg.FILE_EXPORT_DATE,dataIndex:"date_created",width:50,sortable:!1,renderer:Ext.ucf.file.viewHelper().vh_basic},{header:_msg.FILE_DATA_NAME,dataIndex:"data_name",width:120,sortable:!1,renderer:Ext.ucf.file.viewHelper().vh_data_name},{header:_msg.FILE_DATA_SIZE,dataIndex:"data_size",width:20,sortable:!1,renderer:Ext.ucf.file.viewHelper().vh_basic},
{header:_msg.FILE_DOWNLOAD_OPERATOR_ID,dataIndex:"download_operator_id",width:40,sortable:!1,renderer:a.without_operator_link?vh_basic:Ext.ucf.file.viewHelper().vh_download_operator_id},{header:_msg.FILE_DOWNLOAD_COUNT,dataIndex:"download_count",width:20,sortable:!1,renderer:Ext.ucf.file.viewHelper().vh_basic},{header:_msg.FILE_LAST_DOWNLOAD_OPERATOR_ID,dataIndex:"last_download_operator_id",width:120,sortable:!1,renderer:a.without_operator_link?vh_basic:Ext.ucf.file.viewHelper().vh_last_download_operator_id},
{header:_msg.FILE_EXPIRE,dataIndex:"expire_date",width:50,sortable:!1,renderer:Ext.ucf.file.viewHelper().vh_basic},{header:_msg.FILE_DEAL_STATUS,dataIndex:"deal_status",width:30,sortable:!1,renderer:Ext.ucf.file.viewHelper().vh_deal_status},{header:_msg.FLD_TASK_STATUS,dataIndex:"status",width:30,sortable:!1,renderer:Ext.ucf.file.viewHelper().vh_status},{header:_msg.LOG,dataIndex:"log_text",align:"center",width:25,sortable:!1,renderer:Ext.ucf.file.viewHelper().vh_log_text}]});var k=new Ext.grid.GridPanel({store:d,
region:"center",clicksToEdit:1,columnLines:!0,loadMask:!0,viewConfig:{forceFit:!0},stripeRows:!0,bbar:l,tbar:c,cm:f}),h=new Ext.Panel({collapsible:!0,title:a.panel_title,layout:"border",waitMsgTarget:!0,monitorResize:!0,layoutConfig:{columns:1},height:320,items:[k]});g();Ext.ucf.appendLeftMenuChangeDelagate(function(){k.setWidth(h.getWidth()-2)});return h},createImportHistoryGridPanel:function(b,a){a||(a={});a.panel_title||(a.panel_title=_msg.VMSG_IMPORT_HISTORY);a.popup_panel_title||(a.popup_panel_title=
_msg.VMSG_IMPORT);var c=new Ext.data.Store({reader:new Ext.data.JsonReader({idProperty:"unique_id",root:"records",totalProperty:"all_count"},Ext.ucf.file.RecordInfo),url:_vurl+"file/xtlist",autoDestroy:!0}),d=function(){return{start:0,limit:10,data_kind:b}},e=function(){Ext.ucf.search(!1,c,d,"")},g=function(){var c,d=Ext.ucf.file.createCsvImportForm(_vurl+"asynccsvimport",{btn_text:_msg.VMSG_IMPORT},{data_kind:b,file_id:"csvfile"},function(){c.close();e()});return c=new Ext.Window({title:a.popup_panel_title,
layout:"form",modal:!0,width:600,height:200,autoDestory:!0,items:[{xtype:"spacer",height:"30px"},d,{xtype:"spacer",height:"30px"},{xtype:"displayfield",value:"<p>"+_msg.EXP_FILE_UPLOAD+"</p>"}]})},f=new Ext.Button({iconCls:"reflesh",handler:e}),l=new Ext.PagingToolbar({pageSize:10,store:c,displayInfo:!0,displayMsg:_msg.PAGING_BAR,emptyMsg:_msg.NO_DISP_DATA,items:["->"]});f=new Ext.Toolbar({items:[f,"-",{text:_msg.VMSG_IMPORT,handler:function(){var a=g();a.show();a.dd.constrainTo(Ext.getBody())}},
"-"]});var k=new Ext.grid.ColumnModel({columns:[{header:_msg.FILE_IMPORT_DATE,dataIndex:"date_created",width:50,sortable:!1,renderer:Ext.ucf.file.viewHelper().vh_basic},{header:_msg.FILE_DATA_NAME,dataIndex:"data_name",width:120,sortable:!1,renderer:Ext.ucf.file.viewHelper().vh_data_name},{header:_msg.FILE_DATA_SIZE,dataIndex:"data_size",width:20,sortable:!1,renderer:Ext.ucf.file.viewHelper().vh_basic},{header:_msg.FILE_UPLOAD_OPERATOR_ID,dataIndex:"upload_operator_id",width:120,sortable:!1,renderer:Ext.ucf.file.viewHelper().vh_upload_operator_id},
{header:_msg.FILE_DOWNLOAD_COUNT,dataIndex:"download_count",width:20,sortable:!1,renderer:Ext.ucf.file.viewHelper().vh_basic},{header:_msg.FILE_LAST_DOWNLOAD_OPERATOR_ID,dataIndex:"last_download_operator_id",width:40,sortable:!1,renderer:Ext.ucf.file.viewHelper().vh_last_download_operator_id},{header:_msg.FILE_EXPIRE,dataIndex:"expire_date",width:50,sortable:!1,renderer:Ext.ucf.file.viewHelper().vh_basic},{header:_msg.FILE_DEAL_STATUS,dataIndex:"deal_status",width:30,sortable:!1,renderer:Ext.ucf.file.viewHelper().vh_deal_status},
{header:_msg.FLD_TASK_STATUS,dataIndex:"status",width:30,sortable:!1,renderer:Ext.ucf.file.viewHelper().vh_status},{header:_msg.LOG,dataIndex:"log_text",align:"center",width:25,sortable:!1,renderer:Ext.ucf.file.viewHelper().vh_log_text}]}),h=new Ext.grid.GridPanel({store:c,region:"center",clicksToEdit:1,columnLines:!0,loadMask:!0,viewConfig:{forceFit:!0},stripeRows:!0,bbar:l,tbar:f,cm:k}),m=new Ext.Panel({collapsible:!0,title:a.panel_title,layout:"border",waitMsgTarget:!0,monitorResize:!0,layoutConfig:{columns:1},
height:320,items:[h]});e();Ext.ucf.appendLeftMenuChangeDelagate(function(){h.setWidth(m.getWidth()-2)});return m}};
Ext.ucf.file.createFileUpdateField=function(b,a,c,d){c||(c={});void 0==c.btn_text&&(c.btn_text=_msg.VMSG_FILE_ATTACHMENT);void 0==c.btn_only&&(c.btn_only=!1);void 0==c.csrf_token&&(c.csrf_token="");void 0==c.width&&(c.width=400);var e=new Ext.ux.form.FileUploadField({buttonText:c.btn_text,id:b,value:"",name:b,width:c.width,buttonOnly:c.btn_only,listeners:{fileselected:function(a,c){g.getForm()&&g.getForm().isValid()&&g.getForm().submit({params:{file_id:b},waitMsg:_msg.VMSG_MSG_UPLOADING,success:f,
failure:f})}}});c=new Ext.form.Hidden({name:"token",value:c.csrf_token});var g=new Ext.FormPanel({url:a,hideLabel:!0,hideBorders:!0,border:!1,frame:!1,fileUpload:!0,layout:"form",items:[e,c]}),f=function(a,b){a=b.response;if(void 0!=a.responseText&&""!=a.responseText){var c=a.responseText.replace('<pre style="word-wrap: break-word; white-space: pre-wrap;">',"").replace("</pre>","");console.log(a);c=Ext.decode(c);a=c.code;if(0==a)Ext.ucf.dispUpdateMsgByReturnCode(a,c.msg);else if(100==a){a="";for(data in c.vcmsg)a+=
c.vcmsg[data]+"<br/>",b=Ext.getCmp(data),void 0!=b&&(b.preVCMessage=c.vcmsg[data],b.markInvalid(c.vcmsg[data]));Ext.ucf.flowMsg(_msg.VMSG_MSG_ERROR,a)}else""==c.msg?Ext.ucf.dispSysErrMsg():Ext.ucf.flowMsg(_msg.VMSG_MSG_ERROR,c.msg)}else Ext.ucf.dispSysErrMsg();d&&d(c)};g.addEvents("fileupload");return g};
Ext.ucf.file.createCsvImportForm=function(b,a,c,d){a||(a={});void 0==a.btn_text&&(a.btn_text=_msg.VMSG_FILE_ATTACHMENT);void 0==a.btn_only&&(a.btn_only=!1);void 0==a.file_id&&(a.file_id=c.file_id);a=new Ext.ux.form.FileUploadField({buttonText:a.btn_text,id:a.file_id,name:a.file_id,buttonOnly:a.btn_only,width:400,listeners:{fileselected:function(a,b){g()}}});var e=new Ext.FormPanel({id:"csv_import_form",hideLabel:!0,hideBorders:!0,border:!1,frame:!1,fileUpload:!0,layout:"form",items:[a]}),g=function(){if(e.getForm()&&
e.getForm().isValid()){var a=function(a){if(void 0!=a.responseText&&""!=a.responseText)if(a=jQuery.parseJSON(a.responseText),0==a.code){var d=function(a){void 0!=a.responseText&&""!=a.responseText?(a=jQuery.parseJSON(a.responseText),0==a.code?(e.getForm().getEl().dom.action=a.url,e.getForm().submit({params:c,waitMsg:_msg.VMSG_MSG_UPLOADING,success:f,failure:f})):""==a.msg?Ext.ucf.dispSysErrMsg():Ext.ucf.flowMsg(_msg.VMSG_MSG_ERROR,a.msg)):Ext.ucf.dispSysErrMsg()};b+=(-1<b.indexOf("?")?"&":"?")+"token="+
escape(a.token);Ext.Ajax.request({url:_vurl+"createuploadurl",method:"POST",params:{upload_url:b},success:d,failure:d})}else Ext.ucf.dispSysErrMsg();else Ext.ucf.dispSysErrMsg()};Ext.Ajax.request({url:_vurl+"createcsrftoken",method:"GET",params:{},success:a,failure:a})}},f=function(a,b){a=b.response;if(void 0!=a.responseText&&""!=a.responseText){var c=a.responseText.replace('<pre style="word-wrap: break-word; white-space: pre-wrap;">',"").replace("</pre>","");c=Ext.decode(c);a=c.code;0!=a&&(""==c.msg?
Ext.ucf.dispSysErrMsg():Ext.ucf.flowMsg(a,c.msg))}else Ext.ucf.dispSysErrMsg();d&&d(c)};e.addEvents("fileupload");return e};Ext.ucf.file.applicateViewHelper=function(b){var a={},c;for(c in b.fields.keys){var d=b.fields.keys[c],e=Ext.ucf.nvl(b.get(d));a[d]=Ext.ucf.htmlEncode(e)}return a};
Ext.ucf.file.createFileUploadForm=function(){var b=new Ext.ux.form.FileUploadField({buttonText:_msg.VMSG_UPLOAD,id:"loginpage_picture",name:"loginpage_picture",buttonOnly:!1,width:400,listeners:{fileselected:function(b,e){a.getForm()&&a.getForm().isValid()&&a.getForm().submit({params:params,waitMsg:_msg.VMSG_MSG_UPLOADING,success:c,failure:c})}}}),a=new Ext.FormPanel({url:upload_url,hideLabel:!0,hideBorders:!0,border:!1,frame:!1,fileUpload:!0,layout:"form",items:[b]}),c=function(a,b){a=b.response;
void 0!=a.responseText&&""!=a.responseText?(a=a.responseText.replace('<pre style="word-wrap: break-word; white-space: pre-wrap;">',"").replace("</pre>",""),a=Ext.decode(a),b=a.code,0!=b&&(""==a.msg?Ext.ucf.dispSysErrMsg():Ext.ucf.flowMsg(b,a.msg))):Ext.ucf.dispSysErrMsg();uploadwindow.close()};a.addEvents("fileupload");return a};
