Ext.ucf.field=function(){return{createHTMLLinkText:function(a,d){a=new Ext.form.Label({id:a});void 0!=d&&""!=d?(d='<a href="{0}" target="_blank">{1}</a>'.format(d,d),a.html=d):a.text="";return a},createPlaneText:function(a,d,f,g){var b=new Ext.form.Label({id:a});if(f){if(void 0==g||""==g)g=a;var c=f(g,d,b)}a=!1;if(c){a=c.is_html;var e=c.value}a?b.html=e:b.text=e;return b},createTextField:function(a,d,f,g,b,c,e){return new Ext.form.TextField({id:a,name:d,value:f,grow:!0,growMin:b,growMax:2*b,fieldLabel:g,
listeners:{blur:function(){void 0!=c&&(void 0==this.preValue||this.preValue!=this.getValue()?c(this):this.preVCMessage&&this.markInvalid(this.preVCMessage),this.preValue=this.getValue())},afterrender:function(a){"undefined"!=typeof e&&"undefined"!=typeof e.autocomplete&&""!=e.autocomplete&&"undefined"!=typeof a.inputEl&&a.getEl().set({autocomplete:e.autocomplete})}}})},createTextField2:function(a,d,f,g,b,c,e){return new Ext.form.TextField({id:a,name:d,value:f,width:b,fieldLabel:g,listeners:{blur:function(){void 0!=
c&&(void 0==this.preValue||this.preValue!=this.getValue()?c(this):this.preVCMessage&&this.markInvalid(this.preVCMessage),this.preValue=this.getValue())},afterrender:function(a){"undefined"!=typeof e&&"undefined"!=typeof e.autocomplete&&""!=e.autocomplete&&"undefined"!=typeof a.inputEl&&a.getEl().set({autocomplete:e.autocomplete})}}})},createNumberField:function(a,d,f,g,b,c,e){switch(c){case "FLOAT":c="[0-9,-.]";break;default:c="[0-9,-]"}return new Ext.form.TextField({id:a,name:d,value:f,grow:!0,growMin:b,
growMax:2*b,maskRe:new RegExp(c),fieldLabel:g,listeners:{blur:function(){void 0!=e&&(void 0==this.preValue||this.preValue!=this.getValue()?e(this):this.preVCMessage&&this.markInvalid(this.preVCMessage),this.preValue=this.getValue())}}})},createPasswordField:function(a,d,f,g,b,c){return new Ext.form.TextField({id:a,name:d,value:f,grow:!0,growMin:b,growMax:2*b,fieldLabel:g,inputType:"password",listeners:{blur:function(){void 0!=c&&(void 0==this.preValue||this.preValue!=this.getValue()?c(this):this.preVCMessage&&
this.markInvalid(this.preVCMessage),this.preValue=this.getValue())}}})},createTextAreaField:function(a,d,f,g,b,c,e){return new Ext.form.TextArea({id:a,name:d,value:f,width:b,height:c,fieldLabel:g,listeners:{blur:function(){void 0!=e&&(void 0==this.preValue||this.preValue!=this.getValue()?e(this):this.preVCMessage&&this.markInvalid(this.preVCMessage),this.preValue=this.getValue())}}})},createComboBox:function(a,d,f,g,b,c,e){return new Ext.form.ComboBox({id:a,name:d,hiddenName:d,typeAhead:!0,triggerAction:"all",
lazyRender:!1,mode:"local",value:g,store:new Ext.data.ArrayStore({id:0,fields:["Value","Disp"],data:f}),valueField:"Value",displayField:"Disp",fieldLabel:b,selectOnFocus:!0,autoWidth:!1,width:c,editable:!1,listeners:{blur:function(){void 0!=e&&(void 0==this.preValue||this.preValue!=this.getValue()?e(this):this.preVCMessage&&this.markInvalid(this.preVCMessage),this.preValue=this.getValue())}}})},createComboBoxByStore:function(a,d,f,g,b,c,e){var h;return h=new Ext.form.ComboBox({id:a,name:d,hiddenName:d,
typeAhead:!0,triggerAction:"all",lazyRender:!0,mode:"remote",store:new Ext.data.JsonStore({url:f,total:"all_count",root:"records",fields:["Value","Disp"],autoLoad:!0,listeners:{scope:this,load:function(a){h.setValue(g)}}}),valueField:"Value",displayField:"Disp",fieldLabel:b,selectOnFocus:!0,autoWidth:!1,width:c,editable:!1,listeners:{blur:function(){void 0!=e&&(void 0==this.preValue||this.preValue!=this.getValue()?e(this):this.preVCMessage&&this.markInvalid(this.preVCMessage),this.preValue=this.getValue())}}})},
createCheckBox:function(a,d,f,g,b,c){return new Ext.form.Checkbox({id:a,name:d,inputValue:g,checked:f,fieldLabel:b,boxLabel:b,listeners:{blur:function(){void 0!=c&&(void 0==this.preValue||this.preValue!=this.getValue()?c(this):this.preVCMessage&&this.markInvalid(this.preVCMessage),this.preValue=this.getValue())}}})},createCheckBoxGroup:function(a,d,f,g,b,c,e,h,k){e||(e="auto");Ext.each(c,function(a){a.inputValue==f&&(a.checked=!0)});return new Ext.form.CheckboxGroup({id:a,name:d,value:f,width:b,columns:e,
vertical:h,fieldLabel:g,items:c,listeners:{blur:function(){void 0!=k&&(void 0==this.preValue||this.preValue!=this.getValue()?k(this):this.preVCMessage&&this.markInvalid(this.preVCMessage),this.preValue=this.getValue())}}})},createRadioButtonGroup:function(a,d,f,g,b,c,e,h,k){e||(e="auto");Ext.each(c,function(a){a.inputValue==f&&(a.checked=!0)});return new Ext.form.RadioGroup({id:a,name:d,value:f,width:b,columns:e,vertical:h,fieldLabel:g,items:c,listeners:{blur:function(){void 0!=k&&(void 0==this.preValue||
this.preValue!=this.getValue()?k(this):this.preVCMessage&&this.markInvalid(this.preVCMessage),this.preValue=this.getValue())}}})},createDateField:function(a,d,f,g,b,c,e,h){return new Ext.form.DateField({id:a,name:d,value:f,format:h||"Y/m/d",width:b,grow:!0,growMin:b,growMax:2*b,fieldLabel:g,editable:e||!1,listeners:{blur:function(){void 0!=c&&(void 0==this.preValue||this.preValue!=this.getValue()?c(this):this.preVCMessage&&this.markInvalid(this.preVCMessage),this.preValue=this.getValue())}}})},createTimeField:function(a,
d,f,g,b,c){return new Ext.form.TimeField({id:a,name:d,value:f,format:"H:i",width:72,increment:60,grow:!0,growMin:b,growMax:2*b,fieldLabel:g,listeners:{blur:function(){void 0!=c&&(void 0==this.preValue||this.preValue!=this.getValue()?c(this):this.preVCMessage&&this.markInvalid(this.preVCMessage),this.preValue=this.getValue())}}})},createHtmlEditorField:function(a,d,f,g,b,c,e){return new Ext.form.HtmlEditor({id:a,name:d,value:f,width:b,height:c,fieldLabel:g,listeners:{blur:function(){void 0!=e&&(void 0==
this.preValue||this.preValue!=this.getValue()?e(this):this.preVCMessage&&this.markInvalid(this.preVCMessage),this.preValue=this.getValue())}}})},createDateField2:function(a,d,f,g,b){return new Ext.form.DateField({id:a,value:d,format:"Y/m/d",width:f,fieldLabel:g,listeners:{blur:function(){void 0!=b&&(void 0==this.preValue||this.preValue!=this.getValue()?b(this):this.preVCMessage&&this.markInvalid(this.preVCMessage),this.preValue=this.getValue())}}})},init:function(){"outerHTML"in document.createElement("div")||
(HTMLElement.prototype.__defineGetter__("outerHTML",function(){return(new XMLSerializer).serializeToString(this)}),HTMLElement.prototype.__defineGetter__("innerText",function(){return this.textContent}),HTMLElement.prototype.__defineSetter__("innerText",function(a){return this.textContent=a}))}}}();
