var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,c,a){b!=Array.prototype&&b!=Object.prototype&&(b[c]=a.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var b=0;return function(c){return $jscomp.SYMBOL_PREFIX+(c||"")+b++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.iterator;b||(b=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[b]&&$jscomp.defineProperty(Array.prototype,b,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.asyncIterator;b||(b=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.arrayIterator=function(b){var c=0;return $jscomp.iteratorPrototype(function(){return c<b.length?{done:!1,value:b[c++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(b){$jscomp.initSymbolIterator();b={next:b};b[$jscomp.global.Symbol.iterator]=function(){return this};return b};$jscomp.iteratorFromArray=function(b,c){$jscomp.initSymbolIterator();b instanceof String&&(b+="");var a=0,e={next:function(){if(a<b.length){var d=a++;return{value:c(d,b[d]),done:!1}}e.next=function(){return{done:!0,value:void 0}};return e.next()}};e[Symbol.iterator]=function(){return e};return e};
$jscomp.polyfill=function(b,c,a,e){if(c){a=$jscomp.global;b=b.split(".");for(e=0;e<b.length-1;e++){var d=b[e];d in a||(a[d]={});a=a[d]}b=b[b.length-1];e=a[b];c=c(e);c!=e&&null!=c&&$jscomp.defineProperty(a,b,{configurable:!0,writable:!0,value:c})}};$jscomp.polyfill("Array.prototype.keys",function(b){return b?b:function(){return $jscomp.iteratorFromArray(this,function(b){return b})}},"es6","es3");
$jscomp.findInternal=function(b,c,a){b instanceof String&&(b=String(b));for(var e=b.length,d=0;d<e;d++){var f=b[d];if(c.call(a,f,d,b))return{i:d,v:f}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(b,a){return $jscomp.findInternal(this,b,a).v}},"es6","es3");
Ext.ucf.dictionary=function(){var b="";return{viewHelper:function(b,a,e){return{value:a,is_html:!1}},createDictionaryRecord:function(){return Ext.data.Record.create(["unique_id",{name:"keyword",type:"string"},{name:"definition",type:"string"}])},vh_basic:function(b,a,e){return Ext.ucf.htmlEscape(b)},deleteDictionary:function(b){var a=function(a){void 0!=a.responseText&&""!=a.responseText&&(0==jQuery.parseJSON(a.responseText).code?"undefined"!=typeof search&&search():search())};Ext.Msg.show({icon:Ext.MessageBox.WARNING,
title:_msg.CONFIRM,msg:_msg.CONFIRM_DELETE_DICTIONARY,buttons:Ext.Msg.YESNO,fn:function(c,d){"yes"==c&&Ext.Ajax.request({url:_vurl+"dictionary/delete",method:"POST",params:{unique_ids:b},success:a,failure:a})}})},detailDictionary:function(c){var a=function(a){b="";void 0!=a.responseText&&""!=a.responseText&&(a=jQuery.parseJSON(a.responseText),b=a.data.keyword,a=jQuery.parseJSON(a.data.definition),Ext.ucf.dictionary.printDetailDict(a))};Ext.Ajax.request({url:_vurl+"dictionary/xtgetdetail",method:"POST",
params:{unique_id:c},success:a,failure:a})},createTypeField:function(b){b=void 0===b?null:b;var a=[];a.push(["synonym",_msg.SYNONYM]);a=Ext.ucf.field.createComboBox("selectDefinition","selectDefinition",a,"",_msg.SYNONYM,150,null);a.render("FIELD_dict_definition");a.setValue("synonym");Ext.ucf.field.createTextAreaField("tempKeyword","tempKeyword",b,"","98%","40px",Ext.ucf.delegateCheckValidation,{autocomplete:"off"}).render("FIELD_dict_keyword");Ext.ucf.field.createTextField2("tempValue","tempValue",
"","","94%",null).render("FIELD_dict_value")},printDetailDict:function(c){$("#dict-box").empty();var a='<table style="margin-left: 1%" width="98%"><tbody class="detail_layout"><tr><td colspan="5"><img src="/images/share/space.gif" width="10" height="5"  border="0" alt=""></td></tr>'+('<tr><td colspan="5"><p class="style1">'+_msg.EXP_DICTIONARY_REGIST+"</p></td></tr>");a+='<tr><td colspan="5"><div class="main_content_title2">'+_msg.REGISTER_KEYWORD_HEADER+"</div></td></tr>";a+='<tr><td colspan="1" valign="middle" nowrap="" class="style2">'+
_msg.REGISTER_KEYWORD+"</td>";a=a+'<td colspan="2" align="left" class="style3"><div class="field" id="FIELD_dict_keyword"></div></td>'+('<td colspan="2"><p class="style1">&nbsp'+_msg.EXP_REGISTER_KEYWORD+"</p></td></tr>");a=a+'<tr><td colspan="5"><img src="/images/share/space.gif" width="10" height="5"  border="0" alt=""></td></tr>'+('<tr><td colspan="5"><div class="main_content_title2">'+_msg.REGISTER_CONTENT+"</div></td></tr>");a+='<tr><td colspan="1" width="20%" class="style2">'+_msg.REGISTER_TYPE+
"</td>";a=a+'<td colspan="1" width="20%" align="left" class="style3"><div id="FIELD_dict_definition" class="field" ></div></td>'+('<td colspan="1" width="20%" class="style2">'+_msg.REGISTER_VALUE+"</td>");a=a+'<td colspan="1" width="30%" align="left" class="style3"><div class="field" id="FIELD_dict_value"></div></td><td colspan="1"><div id="btnAdd" /></td>'+('<tr><td colspan="5"><p class="style1">'+_msg.EXP_REGISTER_CONTENT+"</p></td></tr>");a+='<tr><td colspan="5"><img src="/images/share/space.gif" width="10" height="5"  border="0" alt=""></td></tr></tbody></table>';
if(0<c.length){a=5<c.length?a+'<div class="definition-value"><table style="margin-left:1%;" id="definition_table" width="99%"><tbody  class="detail_layout">':a+'<div class="definition-value"><table style="margin-left:1%;" id="definition_table" width="95%"><tbody  class="detail_layout">';for(i=0;i<c.length;i++){var e="",d=Object.keys(c[i])[0],f=c[i][d];"synonym"==d&&(e=_msg.SYNONYM);a+='<tr><td colspan="1" width="20%" align="left" class="style2"><label>'+e+'</label><input type="hidden" value="'+d+
'" id="tempDefinitionName'+i+'"></td>';5<c.length?(a+='<td colspan="3" align="left"><input type="text" value="'+f+'" class="x-form-text x-form-field" id="tempDefinitionValue'+i+'" style="width:98%; margin-left:0.6%"></td>',a+='<td colspan="1" align="center" style="width:10%;"><input type="button" title="delete" class="btnTrash" onclick="JavaScript:Ext.ucf.dictionary.saveDefinition('+i+');" /></td></tr>'):(a+='<td colspan="3" align="left"><input type="text" value="'+f+'" class="x-form-text x-form-field" id="tempDefinitionValue'+
i+'" style="width:101%; margin-left:0.6%"></td>',a+='<td colspan="1" align="right" style="width:10%;"><input type="button" title="delete" class="btnTrash" onclick="JavaScript:Ext.ucf.dictionary.saveDefinition('+i+');" /></td></tr>');a+='<tr><td colspan="4"><img src="/images/share/space.gif" width="10" height="5"  border="0" alt=""></td></tr>'}a+="</tbody></table></div>"}$("#dict-box").append(a);Ext.ucf.dictionary.createTypeField(b);(new Ext.Button({text:"&nbsp;&nbsp;&nbsp;&nbsp;"+_msg.VMSG_ADD+"&nbsp;&nbsp;&nbsp;&nbsp;",
type:"submit",handler:function(){Ext.ucf.dictionary.saveDefinition()}})).render(Ext.get("btnAdd"))},getListDefinition:function(){for(var b=[],a=0;a<$("#definition_table").find("tr").length/2;a++){var e="#tempDefinitionValue"+a,d={};d[$("#tempDefinitionName"+a).val().trim()]=$(e).val().trim();b.push(d)}return b},saveDefinition:function(c){var a=Ext.ucf.dictionary.getListDefinition();if("undefined"==String(c))if(""==Ext.getCmp("selectDefinition").value.trim()||""==$("#tempValue").val().trim())Ext.Msg.show({icon:Ext.MessageBox.INFO,
title:_msg.WARNING,msg:_msg.MSG_NEED_CONTENT,buttons:Ext.Msg.OK});else{c=Ext.getCmp("selectDefinition").value.trim();var e=$("#tempValue").val().trim(),d={};d[c]=e;a.push(d);3<a.length&&6>a.length&&$("#dict-box").parent(".x-window-body").css("height",255+28*(a.length-3))}else a.splice(c,1),2<a.length&&5>a.length&&$("#dict-box").parent(".x-window-body").css("height",255+28*(a.length-3));b=$("#tempKeyword").val();Ext.ucf.dictionary.printDetailDict(a)},saveDictionary:function(c,a){var e=Ext.ucf.dictionary.getListDefinition();
if(""==$("#tempKeyword").val().replace(/,/g,"").replace(/\u3001/g,"").trim())Ext.Msg.show({icon:Ext.MessageBox.INFO,title:_msg.WARNING,msg:_msg.MSG_NEED_KEYWORD,buttons:Ext.Msg.OK});else{var d=function(c){if(void 0!=c.responseText&&""!=c.responseText){c=jQuery.parseJSON(c.responseText);var d=c.code;0==d?"undefined"!=typeof search&&(a.close(),b="",search()):""==c.msg?Ext.ucf.dispSysErrMsg(d):Ext.ucf.flowMsg(d,c.msg)}};params={unique_id:c,keyword:$("#tempKeyword").val().trim(),definition:Ext.encode(e)};
console.log(params);Ext.Ajax.request({url:_vurl+"dictionary/edit",method:"POST",params:params,success:d,failure:d})}},createPopupWindowDict:function(c,a){var e=323;3<a&&6>a&&(e+=28*(a-3));5<a&&(e=376);a=new Ext.DataView({labelWidth:30,frame:!1,width:567,height:400,id:"dict-box",layout:"fit"});var d=new Ext.Window({title:_msg.DICTIONARY_REGISTER,layout:"fit",modal:!0,width:606,height:e,resizable:!1,boxMinWidth:400,boxMinHeight:300,plain:!0,autoDestory:!0,id:"dictWindow",hidden:!0,items:a,buttons:[{text:_msg.VMSG_SAVE,
id:"saveDict",handler:function(){event.preventDefault();Ext.ucf.dictionary.saveDictionary(c,d);""!=$("#tempKeyword").val().replace(/,/g,"").replace(/\u3001/g,"").trim()&&$(this).prop("disabled",!0)}},{text:_msg.VMSG_CANCEL,handler:function(){d.close();b=""}}]});d.show();""!=c?Ext.ucf.dictionary.detailDictionary(c):Ext.ucf.dictionary.printDetailDict([])},init:function(){}}}();
