var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");
Ext.ucf.user=function(){return{colsToShow_Influenza:[],viewHelper:function(a,b,c){return{value:b,is_html:!1}},showColumnSetting:function(){console.log("showColumnSetting");var a=[];a.push(Ext.ucf.user.createSaveButton());a.push(new Ext.Button({text:_msg.FLD_CANCEL,handler:function(){Ext.getCmp("window_setting_influenza").close()}}));var b=Ext.ucf.user.createColsToShowGrid();(new Ext.Window({id:"window_setting_influenza",width:670,height:550,maximizable:!0,bodyStyle:"background-color:white;",title:_msg.SETTING_CONFIRM,
plain:!0,autoScroll:!1,layout:"fit",items:[b],buttons:a,listeners:{afterrender:function(){(function(){Ext.ucf.user.GetSettingReport(function(a){a=a.colsToShow;if(""==a||null==a||"[]"==a)Ext.ucf.user.addDefaultRows(),Ext.ucf.user.setDefaultColsToShow();else{Ext.ucf.user.addDefaultRows();var b=Ext.getCmp("cols_to_show_grid_influenza").getStore();a=Ext.decode(a);var c=0;Ext.each(a,function(a){var d=b.find("field",a.field);d=b.getAt(d);d.set("check_enabled",!0);d.set("sort_order",c);c++;var e=MyLang.getMsg(a.header);
e||(e=a.header);d.set("header",e);d.set("width",a.width);"undefined"!=typeof a.custom_field_name&&d.set("custom_field_name",a.custom_field_name);d.commit()});b.sort("sort_order","ASC")}})}).defer(20)}}})).show()},createSaveButton:function(){return new Ext.Button({id:"save_setting_button_influenza",diabled:!0,text:_msg.FLD_UPDATE,handler:function(){var a=[];Ext.getCmp("cols_to_show_grid_influenza").getStore().each(function(b){b.get("check_enabled")&&a.push({header:b.get("header"),field:b.get("field"),
width:b.get("width"),custom_field_name:b.get("custom_field_name")})});var b={colsToShow:Ext.encode(a)};Ext.getCmp("save_setting_button_influenza").disable();Ext.ucf.user.requesUpdateSetting(b,function(a){Ext.getCmp("save_setting_button_influenza").enable();"ok"==a.status?Ext.Msg.show({title:_msg.SETTING_CONFIRM,icon:Ext.MessageBox.INFO,msg:_msg.VMSG_SAVE_SETTING_CONFIRM,buttons:Ext.Msg.OK,fn:function(a){Ext.getCmp("window_setting_influenza").close();location.reload()}}):Ext.ucf.showMessgeBox(_msg.DELEGATE_FUNCTION_USER_CONFIG,
_msg.VMSG_ALERT_UPDATE_FAIL)})}})},loadColsToShow:function(a){Ext.ucf.user.colsToShow_Influenza=a;0==Ext.ucf.user.colsToShow_Influenza.length&&Ext.ucf.user.loadColsToShowDefault();a=Ext.ucf.user.setColsToShow();Ext.ucf.user.colsToShow_Influenza=a},setColsToShow:function(){return Ext.ucf.user.colsToShow_Influenza},loadColsToShowDefault:function(){var a=[];a.push({header:_msg.FLD_USERID,field:"user_id",width:80});a.push({header:_msg.FLD_USERNAME,field:"display_name",width:150});a.push({header:_msg.FLD_USERNAME_KANA,
field:"display_name_kana",width:150});a.push({header:_msg.FLD_MAILADDRESS,field:"mail_address",width:150});a.push({header:_msg.FLD_BIRTHDAY,field:"birthday",width:120});a.push({header:_msg.FLD_LINEWORKSID,field:"lineworks_id",width:120});Ext.ucf.user.colsToShow_Influenza=a},requesUpdateSetting:function(a,b,c){Ext.ucf.user._requestUpdateSettingOid(a,b,c)},_requestUpdateSettingOid:function(a,b,c){"undefined"==typeof c&&(c=1);Ext.Ajax.request({url:_vurl+"user/setcolumns",method:"POST",params:a,success:function(a,
c){a=Ext.decode(a.responseText);b(a)},failure:function(){b({status:"error",error_code:"unknown_error"})}})},GetSettingReport:function(a,b){Ext.ucf.user._GetSettingReportOid(a,b)},_GetSettingReportOid:function(a,b){"undefined"==typeof b&&(b=1);Ext.Ajax.request({url:_vurl+"user/getcolumns",method:"GET",success:function(b,d){b=Ext.decode(b.responseText);a(b)},failure:function(){b<Sateraito.EventController.MAX_RETRY&&Ext.ucf.user._GetSettingReportOid(a,b+1)}})},createColsToShowGrid:function(){var a=new Ext.data.ArrayStore({id:"store_cols_to_show",
fields:[{name:"sort_order",type:"int"},{name:"check_enabled",type:"bool"},{name:"header",type:"string"},{name:"field_display",type:"string"},{name:"field",type:"string"},{name:"custom_field_name",type:"string"},{name:"width",type:"int"},{name:"buttons",type:"string"}]}),b=[{header:_msg.FLD_SORT_ORDER,hidden:!0,width:50,dataIndex:"sort_order"},{header:_msg.FLD_SHOW_OR_NOT,xtype:"checkcolumn",width:36,dataIndex:"check_enabled"},{header:_msg.FLD_DOC_TITLE,width:134,dataIndex:"header",editor:new Ext.form.TextField},
{header:_msg.FLD_COL_WIDTH,width:66,dataIndex:"width",editor:new Ext.form.NumberField},{header:_msg.FLD_CUSTOM_FIELD_NAME,width:126,dataIndex:"custom_field_name",editor:new Ext.form.TextField},{header:_msg.FLD_FIELD_DESCRIPTION,width:198,dataIndex:"field_display"},{header:"",width:50,dataIndex:"buttons"}];b=new Ext.grid.ColumnModel({defaults:{menuDisabled:!0},columns:b});return new Ext.grid.EditorGridPanel({title:_msg.SETTING_CONFIRM,header:!1,id:"cols_to_show_grid_influenza",store:a,stripeRows:!0,
cm:b})},upRow:function(a){var b=Ext.getCmp("cols_to_show_grid_influenza").getStore(),c=b.find("field",a);c=b.getAt(c);var d=c.get("sort_order"),e=-1,f=null;b.each(function(b){if(b.get("field")!=a){var c=b.get("sort_order");c<d&&e<c&&(e=c,f=b.get("field"))}});null!=f&&(c.set("sort_order",e),c=b.find("field",f),b.getAt(c).set("sort_order",d),b.sort("sort_order","ASC"))},downRow:function(a){var b=Ext.getCmp("cols_to_show_grid_influenza").getStore(),c=b.find("field",a);c=b.getAt(c);var d=c.get("sort_order"),
e=1E4,f=null;b.each(function(b){if(b.get("field")!=a){var c=b.get("sort_order");c>d&&e>c&&(e=c,f=b.get("field"))}});null!=f&&(c.set("sort_order",e),c=b.find("field",f),b.getAt(c).set("sort_order",d),b.sort("sort_order","ASC"))},addDefaultRows:function(){var a=Ext.getCmp("cols_to_show_grid_influenza").getStore(),b=a.recordType,c=function(a){return'<span class="link_cmd" title="'+_msg.FLD_MOVE_UP+'" onclick="Ext.ucf.user.upRow(\''+a+'\');">\u25b2</span> <span title="'+_msg.FLD_MOVE_DOWN+'" class="link_cmd" onclick="Ext.ucf.user.downRow(\''+
a+"');\">\u25bc</span>"};a.add(new b({sort_order:1E3,check_enabled:!1,header:_msg.FLD_USERID,field:"user_id",field_display:_msg.FLD_USERID,width:150,buttons:c("user_id")}));a.add(new b({sort_order:1001,check_enabled:!1,header:_msg.FLD_USERNAME,field:"display_name",field_display:_msg.FLD_USERNAME,width:150,buttons:c("display_name")}));a.add(new b({sort_order:1002,check_enabled:!1,header:_msg.FLD_USERNAME_KANA,field:"display_name_kana",field_display:_msg.FLD_USERNAME_KANA,width:150,buttons:c("display_name_kana")}));
a.add(new b({sort_order:1003,check_enabled:!1,header:_msg.FLD_MAILADDRESS,field:"mail_address",field_display:_msg.FLD_MAILADDRESS,width:100,buttons:c("mail_address")}));a.add(new b({sort_order:1004,check_enabled:!1,header:_msg.FLD_BIRTHDAY,field:"birthday",field_display:_msg.FLD_BIRTHDAY,width:150,buttons:c("birthday")}));a.add(new b({sort_order:1005,check_enabled:!1,header:_msg.FLD_LINEWORKSID,field:"lineworks_id",field_display:_msg.FLD_LINEWORKSID,width:200,buttons:c("lineworks_id")}));a.add(new b({sort_order:1006,
check_enabled:!1,header:_msg.FLD_COMMENT,field:"comment",field_display:_msg.FLD_COMMENT,width:100,buttons:c("comment")}));a.add(new b({sort_order:1007,check_enabled:!1,header:_msg.FLD_CONTACT_COMPANY,field:"contact_company",field_display:_msg.FLD_CONTACT_COMPANY,width:100,buttons:c("contact_company")}));a.add(new b({sort_order:1008,check_enabled:!1,header:_msg.FLD_CONTACT_COMPANY_OFFICE,field:"contact_company_office",field_display:_msg.FLD_CONTACT_COMPANY_OFFICE,width:100,buttons:c("contact_company_office")}));
a.add(new b({sort_order:1009,check_enabled:!1,header:_msg.FLD_CONTACT_COMPANY_DEPARTMENT,field:"contact_company_department",field_display:_msg.FLD_CONTACT_COMPANY_DEPARTMENT,width:100,buttons:c("contact_company_department")}));a.add(new b({sort_order:10010,check_enabled:!1,header:_msg.FLD_CONTACT_COMPANY_DEPARTMENT2,field:"contact_company_department2",field_display:_msg.FLD_CONTACT_COMPANY_DEPARTMENT2,width:100,buttons:c("contact_company_department2")}));a.add(new b({sort_order:1011,check_enabled:!1,
header:_msg.FLD_CONTACT_COMPANY_POST,field:"contact_company_post",field_display:_msg.FLD_CONTACT_COMPANY_POST,width:100,buttons:c("contact_company_post")}));a.add(new b({sort_order:10012,check_enabled:!1,header:_msg.FLD_CONTACT_EMAIL1,field:"contact_email1",field_display:_msg.FLD_CONTACT_EMAIL1,width:100,buttons:c("contact_email1")}));a.add(new b({sort_order:10013,check_enabled:!1,header:_msg.FLD_CONTACT_EMAIL2,field:"contact_email2",field_display:_msg.FLD_CONTACT_EMAIL2,width:100,buttons:c("contact_email2")}));
a.add(new b({sort_order:10014,check_enabled:!1,header:_msg.FLD_CONTACT_TEL_NO1,field:"contact_tel_no1",field_display:_msg.FLD_CONTACT_TEL_NO1,width:100,buttons:c("contact_tel_no1")}));a.add(new b({sort_order:10015,check_enabled:!1,header:_msg.FLD_CONTACT_TEL_NO2,field:"contact_tel_no2",field_display:_msg.FLD_CONTACT_TEL_NO2,width:100,buttons:c("contact_tel_no2")}));a.add(new b({sort_order:10016,check_enabled:!1,header:_msg.FLD_CONTACT_TEL_NO3,field:"contact_tel_no3",field_display:_msg.FLD_CONTACT_TEL_NO3,
width:100,buttons:c("contact_tel_no3")}));a.add(new b({sort_order:10017,check_enabled:!1,header:_msg.FLD_CONTACT_TEL_NO4,field:"contact_tel_no4",field_display:_msg.FLD_CONTACT_TEL_NO4,width:100,buttons:c("contact_tel_no4")}));a.add(new b({sort_order:10018,check_enabled:!1,header:_msg.FLD_CONTACT_TEL_NO5,field:"contact_tel_no5",field_display:_msg.FLD_CONTACT_TEL_NO5,width:100,buttons:c("contact_tel_no5")}));a.add(new b({sort_order:10019,check_enabled:!1,header:_msg.FLD_CONTACT_POSTAL_COUNTRY,field:"contact_postal_country",
field_display:_msg.FLD_CONTACT_POSTAL_COUNTRY,width:100,buttons:c("contact_postal_country")}));a.add(new b({sort_order:10020,check_enabled:!1,header:_msg.FLD_CONTACT_POSTAL_CODE,field:"contact_postal_code",field_display:_msg.FLD_CONTACT_POSTAL_CODE,width:100,buttons:c("contact_postal_code")}));a.add(new b({sort_order:10021,check_enabled:!1,header:_msg.FLD_CONTACT_POSTAL_PREFECTURE,field:"contact_postal_prefecture",field_display:_msg.FLD_CONTACT_POSTAL_PREFECTURE,width:100,buttons:c("contact_postal_prefecture")}));
a.add(new b({sort_order:10022,check_enabled:!1,header:_msg.FLD_CONTACT_POSTAL_CITY,field:"contact_postal_city",field_display:_msg.FLD_CONTACT_POSTAL_CITY,width:100,buttons:c("contact_postal_city")}));a.add(new b({sort_order:10023,check_enabled:!1,header:_msg.FLD_CONTACT_POSTAL_STREET_ADDRESS,field:"contact_postal_street_address",field_display:_msg.FLD_CONTACT_POSTAL_STREET_ADDRESS,width:100,buttons:c("contact_postal_street_address")}))},setDefaultColsToShow:function(){var a=Ext.getCmp("cols_to_show_grid_influenza").getStore(),
b=function(b,d){b=a.getAt(a.find("field",b));b.set("check_enabled",!0);b.set("sort_order",d);b.commit()};b("user_id",0);b("display_name",1);b("display_name_kana",2);b("mail_address",3);b("birthday",4);b("lineworks_id",5);a.sort("sort_order","ASC")},createInputName:function(a){(function(a){var b=$("#lbl_custom_attribute"+a).text();var d='<div style="px;padding:10px;"><table border="0" width="100%" cellpadding="2" cellspacing="2" class="detail2" ><tr><td colspan="4"><img src="/images/share/space.gif" width="10" height="10" border="0" alt=""></td></tr><tr>'+
'<td valign="middle" class="style2" nowrap>{0}</td>'.format(_msg.FLD_HEADER_NAME_CURRENT);d=d+'<td align="left" class="style3" colspan="3">'+"<label>{0}</label>".format(b);d=d+'</td></tr><tr><td colspan="4"><img src="/images/share/space.gif" width="10" height="10" border="0" alt=""></td></tr><tr>'+'<td valign="middle" class="style2" nowrap>{0}&nbsp;<font color="red">*</font></td>'.format(_msg.FLD_HEADER_NAME);b=new Ext.FormPanel({labelWidth:30,frame:!1,width:450,layout:"fit",html:d+'<td align="left" class="style3" colspan="3"><input type="text" size="20" autocomplete="off" id="header_name_change" name="header_name_change" class="x-form-text x-form-field" style="width: 242px;"></td></tr><tr><td colspan="4"><img src="/images/share/space.gif" width="10" height="10" border="0" alt=""></td></tr><tr><td colspan="4"><img src="/images/share/space.gif" width="10" height="10" border="0" alt=""></td></tr></table></div>',
buttons:[{text:_msg.VMSG_SAVE,handler:function(){var b=$("#header_name_change").val();""==b?(vc_msgs="["+_msg.FLD_HEADER_NAME+"]"+_msg.VC_NEED,Ext.ucf.flowMsg(_msg.VMSG_MSG_ERROR,vc_msgs,"")):Ext.Ajax.request({url:_vurl+"user/changetitle",method:"POST",params:{header:b,field:"custom_attribute"+a},success:e,failure:e})}},{text:_msg.VMSG_CLOSE,handler:function(){f.close()}}]});var e=function(b){void 0!=b.responseText&&""!=b.responseText&&(0==$.parseJSON(b.responseText).code?(Ext.ucf.flowMsg(_msg.FLD_CHANGE_HEADER_NAME_TITLE,
_msg.PROCESS_RESULT_SUCCESS,""),$("#lbl_custom_attribute"+a).text($("#header_name_change").val()),f.close()):Ext.ucf.flowMsg(_msg.VMSG_MSG_ERROR,_msg.PROCESS_RESULT_FAILED,""))};var f=new Ext.Window({title:_msg.FLD_CHANGE_HEADER_NAME_TITLE,layout:"fit",modal:!0,width:450,height:170,plain:!0,autoDestory:!0,items:b});f.show();f.dd.constrainTo(Ext.getBody())})(a)},init:function(){}}}();
