var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,e){a!=Array.prototype&&a!=Object.prototype&&(a[d]=e.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(d){return $jscomp.SYMBOL_PREFIX+(d||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.arrayIterator=function(a){var d=0;return $jscomp.iteratorPrototype(function(){return d<a.length?{done:!1,value:a[d++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,d){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var e=0,f={next:function(){if(e<a.length){var b=e++;return{value:d(b,a[b]),done:!1}}f.next=function(){return{done:!0,value:void 0}};return f.next()}};f[Symbol.iterator]=function(){return f};return f};
$jscomp.polyfill=function(a,d,e,f){if(d){e=$jscomp.global;a=a.split(".");for(f=0;f<a.length-1;f++){var b=a[f];b in e||(e[b]={});e=e[b]}a=a[a.length-1];f=e[a];d=d(f);d!=f&&null!=d&&$jscomp.defineProperty(e,a,{configurable:!0,writable:!0,value:d})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
Ext.ucf.businessrule=function(){var a={},d={},e={};return{allChannelKinds:"lineworksbot facebookworkplacebotchat linebot facebookbotchat rest mail sateraitoaddon nextsetaddon".split(" "),createChannelObj:function(a,b){if("lineworksbot"==a)return new channels.lineworksbot(b)},trigger_channel:{},action_channels:[],viewHelper:function(f,b,c){var g=b;if("businessrule_unique_id"===f&&(g=b,c&&""!=b)){var k=function(a){var f=a.rule_name;a=a.unique_id;"undefined"!=typeof a?c.setText('<a href="'+_vurl+"businessrule/regist?unqid="+
a+'&tp=rn" target="_blank" >'+Ext.util.Format.htmlEncode(f)+"</a>",!1):c.setText(b,!0)};if(void 0==a[b]||0==a[b])f=function(a){void 0!=a.responseText&&""!=a.responseText&&(a=$.parseJSON(a.responseText),0==a.code?(e[b]=Ext.encode(a.record),k(a.record)):d[b]=!0)},Ext.Ajax.request({url:_vurl+"businessrule/xtruledetail",method:"POST",params:{unique_id:b},success:f,failure:f}),a[b]=!0;else var p=setTimeout(function(){e[b]?(clearTimeout(p),k(Ext.decode(e[b]))):d&&d[b]&&clearTimeout(p)},1E3)}return{value:g,
is_html:!1}},showTriggerConfigPanel:function(a,b){console.log(b);Ext.ucf.businessrule._selectedTriggerChannelObj=void 0;var c=Ext.ucf.businessrule.createChannelObj(a,b.rule_id),f="trigger_panel_area_"+a;$("#trigger_panel_area_"+a).html("");Ext.ucf.businessrule.trigger_channel=null;businessdata_sample_exp_html="";if("undefined"!=typeof c&&null!=c&&c.isActiveAsTrigger.call(c)){a=c.createTriggerConfigPanel.call(c,b.trigger_channel_config,{webhook_url:b.webhook_url,csrf_token:b.csrf_token,vurl:b.vurl,
panel_kind:"trigger"});if("undefined"!=typeof a){(new Ext.Panel({autoScroll:!0,layout:"fit",frame:!1,border:!1,bodyStyle:"background-color:white;padding:5px; font-size:12px;",items:[a],listeners:{}})).render(f);selectedChannelObj=c;Ext.ucf.businessrule._selectedTriggerChannelObj=c;f=function(a){a=jQuery.parseJSON(a.responseText);var c=a.code;0!=c?""==a.msg?Ext.ucf.dispSysErrMsg(c):Ext.ucf.flowMsg(_msg.VMSG_MSG_ERROR,a.msg):(a=a.bot_vo,$("#input_bot_description").text(a.bot_description),$("#input_bot_manager").val(a.bot_manager),
$("#input_bot_url").val(a.bot_url),$("#input_bot_photourl").val(a.bot_photourl),"undefined"!=typeof a.bot_photourl&&""!=a.bot_photourl&&($("#img_bot_icon").attr("src",a.bot_photourl),$("#img_bot_icon").css("display","block"),$("#img_bot_icon_noupload_msg").css("display","none")),Ext.ucf.businessrule.createFileUpdateField("custom_icon",_vurl+"config/xtpictureupload?picture_id=boticon",{csrf_token:b.csrf_token,btn_text:"&nbsp;&nbsp;&nbsp;&nbsp;"+_msg.LINEWORKS_BOT_ICON_UPLOAD+"&nbsp;&nbsp;&nbsp;&nbsp;",
width:0,btn_only:!0},function(a){var c="";a&&(c=a.data_key);console.log(data);$("#input_bot_icon").val(c);a=b.webhook_url.split("/");$("#input_bot_photourl").val(a[0]+"//"+a[2]+"/a/"+a[4]+"/picture/boticon/"+c);(function(){$("#img_bot_icon").attr("src",_vurl+"picture/boticon/"+c+"?uc=n")}).defer(1E3);$("#img_bot_icon").attr("src",_vurl+"picture/boticon/"+c+"?uc=n");$("#img_bot_icon").css("display","block");$("#img_bot_icon_noupload_msg").css("display","none")}),Ext.ucf.file.createFileUpdateField("custom_icon",
_vurl+"config/xtpictureupload?picture_id=boticon",{csrf_token:b.csrf_token,btn_text:"&nbsp;&nbsp;&nbsp;&nbsp;"+_msg.LINEWORKS_BOT_ICON_UPLOAD+"&nbsp;&nbsp;&nbsp;&nbsp;",width:0,btn_only:!0},function(b){console.log(data)}))};a=b.trigger_channel_config.open_api_id;var d=b.trigger_channel_config.bot_no,e=b.trigger_channel_config.consumer_key,l=b.trigger_channel_config.server_id,h=b.trigger_channel_config.priv_key,n={};0<Object.keys(b.trigger_channel_config).length&&(n={open_api_id:a,consumer_key:e,server_id:l,
priv_key:h.replace(/(\n|\r|\t)/g,"").replace(/ /g,"&quot;"),bot_no:d});Ext.Ajax.request({url:_vurl+"lineworksbot/xtgetdetail",method:"POST",params:n,success:f,failure:f})}Ext.ucf.businessrule.trigger_channel=c}},createFileUpdateField:function(a,b,c,d){c||(c={});void 0==c.btn_text&&(c.btn_text=_msg.VMSG_FILE_ATTACHMENT);void 0==c.btn_only&&(c.btn_only=!1);void 0==c.csrf_token&&(c.csrf_token="");void 0==c.width&&(c.width=400);a=new Ext.ux.form.FileUploadField({buttonText:c.btn_text,id:a,value:"",name:a,
width:c.width,buttonOnly:c.btn_only,listeners:{fileselected:function(b,a){f()}}});c=new Ext.form.Hidden({id:"csrf_token",value:c.csrf_token});c=new Ext.FormPanel({url:b,hideLabel:!0,hideBorders:!0,border:!1,frame:!1,id:"test-form",fileUpload:!0,items:[a,c]});var f=function(){$("#test-form").submit(function(){$.ajax({url:b,type:"post",dataType:"application/json",data:$("#test-form").serialize(),success:function(b){console.log(b)}})})};c.addEvents("fileupload");return c},createTriggerConfigPanel:function(a,
b){console.log(b);var c='<table class="info_table"><tr><th nowrap>'+('<div class="main_content_title2">'+Ext.ucf.htmlEscape(_msg.FLD_CHANNEL_KIND)+"</div>");c=c+'</th><td><div id="trigger_channel_kind_area" ></div>'+('<p><font color="#696969">'+Ext.ucf.htmlEscape(_msg.EXP_TRIGGER_CHANNEL_KIND)+"</font></p>");var f;new Ext.Panel({html:c+'</td><td>&nbsp;&nbsp;</td><td><div id="businessdata_sample_btn_area" ></div></td></tr><tr class="space" ><td colspan="4" ><img src="/images/spacer.gif" alt="" /></td></tr><tr><th nowrap>&nbsp;</th><td colspan="3" ><div id="trigger_setting_panel" ></div></td></tr></table>',
renderTo:a,border:!1,listeners:{afterRender:function(){new Ext.Button({text:"&nbsp;"+Ext.ucf.htmlEscape(_msg.BUSINESSDATA_EXP)+"&nbsp;",id:"businessdata_sample_btn",renderTo:"businessdata_sample_btn_area",handler:function(){var b=new Ext.Panel({frame:!1,border:!1,width:600,autoScroll:!0,bodyStyle:"background-color:white;padding:5px; font-size:13px;",html:f.getBusinessDataAsTriggerExpHtml.call(f),buttons:[{text:_msg.VMSG_CLOSE,handler:function(){a.close()}}]});var a=new Ext.Window({title:_msg.BUSINESSDATA_EXP+
" ["+f.channel_title+"]",layout:"fit",modal:!0,width:700,height:500,plain:!0,autoDestory:!0,items:[b]});a.show();a.dd.constrainTo(Ext.getBody())}});var a=[];Ext.each(Ext.ucf.businessrule.allChannelKinds,function(b){b=Ext.ucf.businessrule.createChannelObj(b,"dummy");"undefined"!=typeof b&&b.isActiveAsTrigger.call(b)&&a.push([b.channel_kind,b.channel_title])});var c=[];c.push(["",_msg.SELECT_CHANNEL_KIND]);for(var d=0;d<a.length;d++){var e=a[d];c.push([e[0],e[1]])}var g=new Ext.form.ComboBox({id:"trigger_channel_kind",
valueField:"value",displayField:"disp",name:"trigger_channel_kind",hiddenName:"trigger_channel_kind",store:new Ext.data.ArrayStore({id:0,fields:["value","disp"],data:c}),triggerAction:"all",editable:!1,forceSelection:!0,value:b.trigger_channel_kind,width:400,renderTo:"trigger_channel_kind_area",mode:"local"}),m=function(){Ext.ucf.businessrule._selectedTriggerChannelObj=void 0;var a=Ext.ucf.businessrule.createChannelObj(g.getValue(),b.rule_id);$("#trigger_setting_panel").html("");Ext.ucf.businessrule.trigger_channel=
null;businessdata_sample_exp_html="";Ext.getCmp("businessdata_sample_btn").hide();if("undefined"!=typeof a&&null!=a&&a.isActiveAsTrigger.call(a)){var c=a.createTriggerConfigPanel.call(a,b.trigger_channel_config,{webhook_url:b.webhook_url});"undefined"!=typeof c&&((new Ext.Panel({autoScroll:!0,layout:"fit",frame:!1,border:!1,bodyStyle:"background-color:white;padding:5px; font-size:12px;",items:[c],listeners:{}})).render("trigger_setting_panel"),f=a,Ext.ucf.businessrule._selectedTriggerChannelObj=a,
Ext.getCmp("businessdata_sample_btn").show());Ext.ucf.businessrule.trigger_channel=a}};g.addListener("select",function(){m()});m()}},autoScroll:!0})},createTriggerConfigJson:function(){if("undefined"!=typeof Ext.ucf.businessrule.trigger_channel&&null!=Ext.ucf.businessrule.trigger_channel)return Ext.ucf.businessrule.trigger_channel.createTriggerChannelConfigJson()},createLogicConfigJson:function(){return{script:Ext.ComponentMgr.get("logic_script").getValue()}},setValidationMessageToLogicConfig:function(a){a=
"undefined"!=typeof a?a:"";""!=a?Ext.ComponentMgr.get("logic_script").markInvalid(a):Ext.ComponentMgr.get("logic_script").isValid(!0);$("#vc_msg_logic_script").html(Ext.ucf.htmlEncode(a))},createActionConfigJson:function(){if("undefined"!=typeof Ext.ucf.businessrule.action_channels&&null!=Ext.ucf.businessrule.action_channels){for(var a=[],b=0;b<Ext.ucf.businessrule.action_channels.length;b++){var c=Ext.ucf.businessrule.action_channels[b],d=c.createActionChannelConfigJson.call(c);d.__channel_title__=
Ext.ComponentMgr.get("action_panel_title_"+c.instanceId()).getValue();d.__channel_kind__=Ext.ComponentMgr.get("action_channel_kind_"+c.instanceId()).getValue();a.push(d)}return a}},checkValidationTriggerChannelConfig:function(){var a=[],b=Ext.ComponentMgr.get("trigger_channel_kind");""==b.getValue()&&(a.push("["+_msg.FLD_CHANNEL_KIND+"]"+_msg.VC_NEED),b.markInvalid(_msg.VC_NEED));b=Ext.ucf.businessrule.trigger_channel;if("undefined"!=typeof b&&null!=b&&(b=b.checkValidationTriggerChannelConfig.call(b),
"undefined"!=typeof b&&null!=b))for(var c=0;c<b.length;c++)a.push(b[c]);return a},checkValidationTriggerChannelConfigCreate:function(){var a=[],b=Ext.ucf.businessrule.trigger_channel;if("undefined"!=typeof b&&null!=b&&(b=b.checkValidationTriggerChannelConfig.call(b),"undefined"!=typeof b&&null!=b))for(var c=0;c<b.length;c++)a.push(b[c]);return a},checkValidationActionChannelConfig:function(){var a=[];if("undefined"!=typeof Ext.ucf.businessrule.action_channels&&null!=Ext.ucf.businessrule.action_channels)for(var b=
0;b<Ext.ucf.businessrule.action_channels.length;b++){var c=Ext.ucf.businessrule.action_channels[b],d=c.checkValidationActionChannelConfig.call(c);if("undefined"!=typeof d&&null!=d)for(var e=0;e<d.length;e++)a.push(d[e]);c=Ext.ComponentMgr.get("action_panel_title_"+c.instanceId());d=c.getValue();""==d&&(a.push("["+_msg.VMSG_CHANNEL_TITLE+"]"+_msg.VC_NEED),c.markInvalid(_msg.VC_NEED));50<d.length&&(a.push("["+_msg.VMSG_CHANNEL_TITLE+"]"+_msg.VC_MAXLENGTH+"50"),c.markInvalid(_msg.VC_MAXLENGTH+"50"))}return a},
createTestCallButton:function(a){return new Ext.Button({text:_msg.BTN_TEST_EXECUTION,type:"button",margins:{top:5,right:5,bottom:5,left:5},handler:function(){var b;"undefined"!=typeof Ext.ucf.businessrule._selectedTriggerChannelObj&&(b=Ext.ucf.businessrule._selectedTriggerChannelObj.getBusinessDataAsTriggerSample.call(Ext.ucf.businessrule._selectedTriggerChannelObj));"undefined"==typeof b&&(b={email:"senduser@yourdomain.com",content:"send message contents(sample)"});b=new Ext.Panel({title:"",deferredRender:!1,
layout:"table",frame:!1,border:!1,bodyStyle:"margin:0px; padding:5px; font-size:12px;",defaults:{margin:"5px",padding:"5px"},layoutConfig:{tableAttrs:{style:{margin:"5px",padding:"5px"}},columns:2},items:[{xtype:"label",colspan:2,text:_msg.EXP_TEST_EXECUTION},{xtype:"textarea",id:"test_contents",value:JSON.stringify(b,null,"    "),width:"98%",height:200,colspan:2,emptyText:_msg.TEST_CONTENTS_EMPTYTEXT.replace(/\r?\n/g," ")},{xtype:"label",colspan:2,html:'<span style="color:red;" id="vc_msg_test_contents"></span>'},
{xtype:"button",style:{margin:"5px 0px 5px 0px"},text:"&nbsp;"+_msg.BTN_TEST_EXECUTION_SCRIPT+"&nbsp;",colspan:1,handler:function(){var a=function(a){void 0!=a.responseText&&""!=a.responseText&&(a=$.parseJSON(a.responseText),0==a.code?(a=a.contents,""!=a&&(a=JSON.stringify(JSON.parse(a),null,"    ")),Ext.getCmp("edited_contents").setValue(a),Ext.getCmp("text_execute_action_btn").setDisabled(!1)):(Ext.ucf.flowMsg(_msg.VMSG_MSG_ERROR,a.msg),Ext.getCmp("test_contents").markInvalid(a.msg),$("#vc_msg_test_contents").html(Ext.ucf.htmlEncode(a.msg))))};
$("#vc_msg_test_contents").html("");var b={type:"logic",logic_script:Ext.getCmp("logic_script").getValue(),contents:Ext.getCmp("test_contents").getValue()};Ext.Ajax.request({url:_vurl+"businessrule/xtcallbusinessrule",method:"POST",params:b,success:a,failure:a})}},{xtype:"label",colspan:1,style:{margin:"0px 0px 0px 10px"},html:_msg.EXP_BTN_TEST_EXECUTION_SCRIPT},{xtype:"textarea",id:"edited_contents",readOnly:!0,value:"",width:"98%",height:200,colspan:2,emptyText:""},{xtype:"label",colspan:2,html:'<span style="color:red;" id="vc_msg_edited_contents"></span>'},
{xtype:"button",id:"text_execute_action_btn",disabled:!0,style:{margin:"5px 0px 5px 0px"},text:"&nbsp;"+_msg.BTN_TEST_EXECUTION_ACTION+"&nbsp;",colspan:1,handler:function(){var b=function(a){void 0!=a.responseText&&""!=a.responseText&&(a=$.parseJSON(a.responseText),0==a.code?Ext.ucf.flowMsg(_msg.SUCCESS,_msg.VMSG_FIN_TEST_CALL_ACTION,""):(Ext.ucf.flowMsg(_msg.VMSG_MSG_ERROR,a.msg),Ext.getCmp("edited_contents").markInvalid(a.msg),$("#vc_msg_edited_contents").html(Ext.ucf.htmlEncode(a.msg))))},c=Ext.ucf.businessrule.createTriggerAndLogicAndActionJsonsWithVC();
c.is_ok?confirm(_msg.VMSG_CONFIRM_TEST_CALL_ACTION)&&(c={type:"action",rule_id:a,action_channel_config:c.action_channel_config,contents:Ext.getCmp("test_contents").getValue(),edited_contents:Ext.getCmp("edited_contents").getValue()},$("#vc_msg_test_contents").html(""),Ext.Ajax.request({url:_vurl+"businessrule/xtcallbusinessrule",method:"POST",params:c,success:b,failure:b})):Ext.ucf.flowMsg(_msg.VMSG_MSG_ERROR,c.vc_msg,"")}},{xtype:"label",colspan:1,style:{margin:"0px 0px 0px 10px"},html:_msg.EXP_BTN_TEST_EXECUTION_ACTION}]});
var c=new Ext.Window({title:_msg.TITLE_TEST_EXECUTION,layout:"fit",modal:!0,width:700,height:600,plain:!0,autoDestory:!0,buttons:[{text:_msg.VMSG_CLOSE,handler:function(){c.close()}}],items:[b]});c.show();c.dd.constrainTo(Ext.getBody())}})},createLogicConfigPanel:function(a,b){b="undefined"!=typeof b?b:{};var c="undefined"!=typeof b.logic_config?b.logic_config:{},d=[],e=new Ext.Button({text:_msg.BTN_CHECK_SCRIPT_GRAMMER,type:"button",margins:{top:5,right:5,bottom:5,left:5},handler:function(){var a=
function(a){void 0!=a.responseText&&""!=a.responseText&&(a=$.parseJSON(a.responseText),0==a.code?(Ext.ucf.flowMsg(_msg.VMSG_CHECK_SCRIPT_GRAMMER,_msg.VMSG_FIN_CHECK_SCRIPT_GRAMMER_SUCCESS,""),Ext.ucf.businessrule.setValidationMessageToLogicConfig("")):(Ext.ucf.flowMsg(_msg.VMSG_CHECK_SCRIPT_GRAMMER,a.msg),Ext.ucf.businessrule.setValidationMessageToLogicConfig(a.msg)))},b={type:"checkgrammer",logic_script:Ext.getCmp("logic_script").getValue()};Ext.ucf.businessrule.setValidationMessageToLogicConfig("");
Ext.Ajax.request({url:_vurl+"businessrule/xtcallbusinessrule",method:"POST",params:b,success:a,failure:a})}});b=Ext.ucf.businessrule.createTestCallButton(b.rule_id);e=[e,{xtype:"label",html:"&nbsp;&nbsp;"},b];e=new Ext.Panel({title:"",deferredRender:!1,layout:"table",frame:!1,border:!1,bodyStyle:"padding:20 0 5 0; font-size:14px;",layoutConfig:{tableAttrs:{style:{margin:"0 0 5px 0"}},columns:e.length},items:e});d.push(e);d.push(new Ext.form.TextArea({id:"logic_script",value:"undefined"!=typeof c.script?
c.script:"",width:800,height:600,emptyText:_msg.BUSINESSRULE_LOGICSCRIT_EMPTYTEXT.replace(/\r?\n/g," "),listeners:{specialkey:function(a,b){if(b.getKey()==b.TAB)if(b.stopEvent(),a=a.el.dom,a.setSelectionRange){b=a.value.substring(0,a.selectionStart)+"\t";var c=b.length;a.value=b+a.value.substring(a.selectionEnd,a.value.length);a.setSelectionRange(c,c)}else document.selection&&(document.selection.createRange().text="\t")}}}));c=new Ext.Panel({html:'<table class="info_table"><tr><td><span style="color:red;" id="vc_msg_logic_script"></span></td></tr></table>',
border:!1,autoScroll:!0});d.push(c);new Ext.Panel({renderTo:a,border:!1,autoScroll:!0,items:d})},createActionConfigPanel:function(a,b){var c=[];Ext.each(Ext.ucf.businessrule.allChannelKinds,function(a){a=Ext.ucf.businessrule.createChannelObj(a,"dummy");"undefined"!=typeof a&&a.isActiveAsAction.call(a)&&c.push([a.channel_kind,a.channel_title])});var d='<table class="info_table"><tr><th nowrap></th><td><select id="action_channel_kind" >'+('<option value="" >'+Ext.ucf.htmlEscape(_msg.SELECT_CHANNEL_KIND)+
"</option>");for(var e=0;e<c.length;e++){var f=c[e];d+='<option value="'+Ext.ucf.htmlEscape(f[0])+'" >'+Ext.ucf.htmlEscape(f[1])+"</option>"}d=d+'</select></td><td>&nbsp;</td><td><div id="add_action_channel" ></div></td></tr><tr><td></td><td colspan="3" >'+('<p><font color="#696969">'+Ext.ucf.htmlEscape(_msg.EXP_ACTION_CHANNEL_KIND)+"</font></p>");var l={},h,n=function(a,b){var c=l[a.instanceId()];if("undefined"!=typeof c){var d=new Ext.Panel({height:"90%",autoScroll:!1,layout:"table",layoutConfig:{tableAttrs:{style:{padding:"5px"}},
columns:5},frame:!1,border:!1,bodyStyle:"background-color:white;padding:5px; font-size:12px;",items:[{xtype:"label",text:_msg.VMSG_CHANNEL_TITLE+": ",colspan:1},{xtype:"textfield",id:"action_panel_title_"+a.instanceId(),value:"undefined"!=typeof b.__channel_title__?b.__channel_title__:a.channel_title,width:"300px",cls:"action-panel-title",height:20,listeners:{change:function(){var a=this.id.replace("action_panel_title_","");Ext.ComponentMgr.get("action_panel_container"+a).setTitle(""!=this.getValue()?
this.getValue():_msg.VMSG_NOINDICATE)}},colspan:1},{border:!1,html:"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;",padding:"0 0 0 10",colspan:1},{xtype:"button",id:"btn_remove_action_channel_"+a.instanceId(),text:_msg.BTN_REMOVE_CHANNEL,handler:function(){var a=this.id.replace("btn_remove_action_channel_","");if(confirm(_msg.CONFIRM_REMOVE_CHANNEL)){for(var b=0;b<Ext.ucf.businessrule.action_channels.length;b++)Ext.ucf.businessrule.action_channels[b].instanceId()==a&&(Ext.ucf.businessrule.action_channels.splice(b--,
1),h.remove(Ext.ComponentMgr.get("action_panel_container"+a)));h.activate(0)}},colspan:1},{xtype:"hidden",id:"action_channel_kind_"+a.instanceId(),value:a.channel_kind,colspan:1}]});b=b.__channel_title__;if("undefined"==typeof b||""==b)b=a.channel_title;if("undefined"==typeof b||""==b)b=_msg.VMSG_NOINDICATE;a=new Ext.Panel({title:b,id:"action_panel_container"+a.instanceId(),autoScroll:!0,boxMinHeight:300,frame:!1,border:!0,bodyStyle:"background-color:white;padding:5px;font-size:12px;margin-bottom:5px;",
items:[d,c],listeners:{}});h.add(a)}},m=[["user_id",_msg.FLD_USERID],["employee_id",_msg.FLD_EMPLOYEEID],["lineworks_id",_msg.FLD_LINEWORKSID],["line_id",_msg.FLD_LINEID],["facebookworkplace_id",_msg.FLD_FACEBOOKWORKPLACEID],["facebook_id",_msg.FLD_FACEBOOKID],["mail_address",_msg.FLD_MAILADDRESS]];new Ext.Panel({html:d+'</td></tr><tr class="space" ><td colspan="4" ><img src="/images/spacer.gif" alt="" /></td></tr><tr><th nowrap>&nbsp;</th><td colspan="3" ><div id="action_setting_panel" ></div></td></tr></table>',
renderTo:a,border:!1,listeners:{bodyResize:function(a,b,c){h.setWidth(.9*b)},afterRender:function(){h=new Ext.TabPanel({id:"action_channel_tabpanel",height:750,width:950,enableTabScroll:!0,deferredRender:!1,plain:!0,bodyStyle:"background-color:white;",region:"center",listeners:{afterRender:function(){if("undefined"!=typeof b.action_channel_config)for(var a=0;a<b.action_channel_config.length;a++){var c=b.action_channel_config[a],d=Ext.ucf.businessrule.createChannelObj(c.__channel_kind__,b.rule_id);
"undefined"!=typeof d&&null!=d&&d.isActiveAsAction.call(d)&&(Ext.ucf.businessrule.action_channels.push(d),l[d.instanceId()]=d.createActionConfigPanel.call(d,c,{data_mapping_to_type_items:m}),d.instanceId(),n(d,c))}else d=Ext.ucf.businessrule.createChannelObj("linebot",b.rule_id),"undefined"!=typeof d&&null!=d&&d.isActiveAsAction.call(d)&&(Ext.ucf.businessrule.action_channels.push(d),l[d.instanceId()]=d.createActionConfigPanel.call(d,{},{data_mapping_to_type_items:m}),d.instanceId(),n(d,{}),h.activate(h.items.length-
1));for(a=0;a<h.items.length;a++)h.activate(a);h.activate(0)}},items:[]});h.render("action_setting_panel");new Ext.Button({text:"&nbsp;"+Ext.ucf.htmlEscape(_msg.ADD_CHANNEL)+"&nbsp;",renderTo:"add_action_channel",handler:function(){var a=$("#action_channel_kind").val();a=Ext.ucf.businessrule.createChannelObj(a,b.rule_id);"undefined"!=typeof a&&null!=a&&a.isActiveAsAction.call(a)&&(Ext.ucf.businessrule.action_channels.push(a),l[a.instanceId()]=a.createActionConfigPanel.call(a,{},{data_mapping_to_type_items:m}),
a.instanceId(),n(a,{}),h.activate(h.items.length-1))}})}},autoScroll:!0})},createTriggerAndLogicAndActionJsonsWithVC:function(){var a=[],b=Ext.ucf.businessrule.checkValidationTriggerChannelConfig();if("undefined"!=typeof b&&null!=b)for(var c=0;c<b.length;c++)a.push(b[c]);b=Ext.ucf.businessrule.checkValidationActionChannelConfig();if("undefined"!=typeof b&&null!=b)for(c=0;c<b.length;c++)a.push(b[c]);if(0<a.length){b="";for(c=0;c<a.length;c++)b+=a[c]+"<br/>";return{is_ok:!1,vc_msg:b}}a="";c=Ext.ucf.businessrule.createTriggerConfigJson();
"undefined"!=typeof c&&(a=Ext.encode(c));c="";b=Ext.ucf.businessrule.createLogicConfigJson();"undefined"!=typeof b&&(c=Ext.encode(b));b="";var d=Ext.ucf.businessrule.createActionConfigJson();"undefined"!=typeof d&&(b=Ext.encode(d));return{trigger_channel_config:a,logic_config:c,action_channel_config:b,is_ok:!0}},createTriggerAndLogicAndActionJsonsWithVC2:function(){var a=[],b=Ext.ucf.businessrule.checkValidationTriggerChannelConfigCreate();if("undefined"!=typeof b&&null!=b)for(var c=0;c<b.length;c++)a.push(b[c]);
Ext.ucf.businessrule.checkValidationActionChannelConfig();if(0<a.length){b="";for(c=0;c<a.length;c++)b+=a[c]+"<br/>";return{is_ok:!1,vc_msg:b}}a="";c=Ext.ucf.businessrule.createTriggerConfigJson();"undefined"!=typeof c&&(a=Ext.encode(c));c="";b=Ext.ucf.businessrule.createActionConfigJson();"undefined"!=typeof b&&(c=Ext.encode(b));return{trigger_channel_config:a,logic_config:"",action_channel_config:c,is_ok:!0}},init:function(){}}}();
Ext.ucf.businessrule.trigger=function(){return{createHistoryRecord:function(){return Ext.data.Record.create([{name:"unique_id",type:"string",mapping:"unique_id"},{name:"businessrule_unique_id",type:"string"},{name:"rule_id",type:"string"},{name:"access_datetime",type:"string"},{name:"channel_kind",type:"string"},{name:"status",type:"string"},{name:"is_test_execution",type:"bool"},{name:"client_ip",type:"string"},{name:"user_agent",type:"string"},{name:"log_text",type:"string"}])},vh_businessrule_unique_id:function(a,
d,e){return'<div id="FIELD_businessrule_unique_id_'+e.get("unique_id")+'" class="field" ></div>'},vh_channel_kind:function(a,d,e){e.get("is_test_execution")?a=Ext.ucf.htmlEscape(_msg.TESTCALL):(d=Ext.ucf.businessrule.createChannelObj(a,"dummy"),a="undefined"!=typeof d?d.channel_title:a);return a},vh_status:function(a,d,e){return"SUCCESS"==a?_msg.SUCCESS:"FAILED"==a?_msg.FAILED:a},vh_contents:function(a,d,e){return"<a href=\"JavaScript:Ext.ucf.businessrule.trigger.dispDetail('"+e.get("unique_id")+
"', 'contents')\" >"+_msg.HISTORY_CONTENTS+"</a>"},vh_log_text:function(a,d,e){a="";"undefined"!=typeof e.get("log_text")&&""!=e.get("log_text")&&(a+="<a href=\"JavaScript:Ext.ucf.businessrule.trigger.dispDetail('"+e.get("unique_id")+"', 'log_text')\" >"+_msg.LOG+"</a>");return a},vh_action_historys:function(a,d,e){return"<a href=\"JavaScript:Ext.ucf.businessrule.action.dispHistoryWindow('"+e.get("businessrule_unique_id")+"', '"+e.get("unique_id")+"')\" >"+_msg.HISTORY_ACTION_HISTORYS+"</a>"},vh_basic:function(a,
d,e){return Ext.ucf.htmlEscape(a)},dispDetail:function(a,d){var e=function(a){a=new Ext.FormPanel({labelWidth:30,frame:!1,width:900,layout:"fit",items:[{xtype:"fieldset",autoHeight:!0,autoWidth:!0,defaults:{width:600,height:400},defaultType:"textarea",items:[{fieldLabel:"",name:"text_data",value:a,readOnly:!0}]}],buttons:[{text:_msg.VMSG_CLOSE,handler:function(){e.close()}}]});var b="";"contents"==d&&(b=_msg.HISTORY_CONTENTS);"log_text"==d&&(b=_msg.LOG);"target_user_ids"==d&&(b=_msg.HISTORY_TARGET_USERS);
var e=new Ext.Window({title:b,layout:"fit",modal:!0,width:700,height:500,plain:!0,autoDestory:!0,items:a});e.show();e.dd.constrainTo(Ext.getBody())},f=function(a){void 0!=a.responseText&&""!=a.responseText&&(a=$.parseJSON(a.responseText),0==a.code&&(a=a.record[d],"contents"==d&&""!=a?a=JSON.stringify(JSON.parse(a),null,"    "):"target_user_ids"==d&&""!=a&&(a=a.replace(",","\n")),e(a)))};Ext.Ajax.request({url:_vurl+"businessrule/xttriggerhistorydetail",method:"POST",params:{unique_id:a},success:f,
failure:f})},createHistoryGrid:function(a){var d=new Ext.data.Store({reader:new Ext.data.JsonReader({idProperty:"unique_id",root:"records",totalProperty:"all_count"},Ext.ucf.businessrule.trigger.createHistoryRecord()),url:_vurl+"businessrule/xttriggerhistorylist",autoDestroy:!0});if("undefined"==typeof a||""==a)d.on("load",function(a,b,c){Ext.each(b,function(a){Ext.ucf.field.createPlaneText("businessrule_unique_id_"+a.get("unique_id"),a.get("businessrule_unique_id"),Ext.ucf.businessrule.viewHelper,
"businessrule_unique_id").render("FIELD_businessrule_unique_id_"+a.get("unique_id"))})});var e=function(){return{start:0,limit:10,sk_businessrule_unique_id:a}},f=function(){Ext.ucf.search(!1,d,e,"")},b=new Ext.Button({iconCls:"reflesh",handler:f}),c=new Ext.PagingToolbar({pageSize:10,store:d,displayInfo:!0,displayMsg:_msg.PAGING_BAR,emptyMsg:_msg.NO_DISP_DATA,items:["->"]});b=new Ext.Toolbar({items:[b]});var g=[];g.push({header:_msg.HISTORY_ACCESSDATETIME,dataIndex:"access_datetime",width:70,sortable:!1,
renderer:Ext.ucf.businessrule.trigger.vh_basic});"undefined"!=typeof a&&""!=a||g.push({header:_msg.HISTORY_BUSINESSRULE_ID,dataIndex:"businessrule_unique_id",width:150,sortable:!1,renderer:Ext.ucf.businessrule.trigger.vh_businessrule_unique_id});g.push({header:_msg.HISTORY_CHANNELKIND,dataIndex:"channel_kind",width:70,sortable:!1,renderer:Ext.ucf.businessrule.trigger.vh_channel_kind});g.push({header:_msg.HISTORY_CLIENTIP,dataIndex:"client_ip",width:50,sortable:!1,renderer:Ext.ucf.businessrule.trigger.vh_basic});
g.push({header:_msg.HISTORY_STATUS,dataIndex:"status",width:50,sortable:!1,renderer:Ext.ucf.businessrule.trigger.vh_status});g.push({header:_msg.HISTORY_ACTION_HISTORYS,dataIndex:"",align:"center",width:40,sortable:!1,renderer:Ext.ucf.businessrule.trigger.vh_action_historys});g.push({header:_msg.HISTORY_CONTENTS,dataIndex:"contents",align:"center",width:40,sortable:!1,renderer:Ext.ucf.businessrule.trigger.vh_contents});g.push({header:_msg.LOG,dataIndex:"log_text",align:"center",width:40,sortable:!1,
renderer:Ext.ucf.businessrule.trigger.vh_log_text});g=new Ext.grid.ColumnModel({columns:g});c=new Ext.grid.GridPanel({store:d,region:"center",columnLines:!0,loadMask:!0,viewConfig:{forceFit:!0},stripeRows:!0,bbar:c,tbar:b,cm:g});return new Ext.Panel({collapsible:!1,title:_msg.VMSG_BUSINESSRULE_HISTORY,layout:"border",waitMsgTarget:!0,monitorResize:!0,layoutConfig:{columns:1},listeners:{afterRender:function(){f()}},height:320,items:[c]})},init:function(){}}}();
Ext.ucf.businessrule.action=function(){return{createHistoryRecord:function(){return Ext.data.Record.create([{name:"unique_id",type:"string",mapping:"unique_id"},{name:"businessrule_unique_id",type:"string"},{name:"rule_id",type:"string"},{name:"trigger_unique_id",type:"string"},{name:"estimated_datetime",type:"string"},{name:"execute_datetime",type:"string"},{name:"channel_kind",type:"string"},{name:"status",type:"string"},{name:"is_test_execution",type:"bool"},{name:"target_user_ids",type:"string"},
{name:"log_text",type:"string"}])},vh_businessrule_unique_id:function(a,d,e){return'<div id="FIELD_businessrule_unique_id_'+e.get("unique_id")+'" class="field" ></div>'},vh_channel_kind:function(a,d,e){d=Ext.ucf.businessrule.createChannelObj(a,"dummy");return"undefined"!=typeof d?d.channel_title:a},vh_status:function(a,d,e){a="SUCCESS"==a?Ext.ucf.htmlEscape(_msg.SUCCESS):"FAILED"==a?Ext.ucf.htmlEscape(_msg.FAILED):a;e.get("is_test_execution")&&(a=a+" ("+Ext.ucf.htmlEscape(_msg.TESTCALL)+")");return a},
vh_contents:function(a,d,e){return"<a href=\"JavaScript:Ext.ucf.businessrule.action.dispDetail('"+e.get("unique_id")+"', 'contents')\" >"+_msg.HISTORY_CONTENTS+"</a>"},vh_log_text:function(a,d,e){a="";"undefined"!=typeof e.get("log_text")&&""!=e.get("log_text")&&(a+="<a href=\"JavaScript:Ext.ucf.businessrule.action.dispDetail('"+e.get("unique_id")+"', 'log_text')\" >"+_msg.LOG+"</a>");return a},vh_target_user_ids:function(a,d,e){a="";"undefined"!=typeof e.get("target_user_ids")&&""!=e.get("target_user_ids")&&
(a+="<a href=\"JavaScript:Ext.ucf.businessrule.action.dispDetail('"+e.get("unique_id")+"', 'target_user_ids')\" >"+_msg.HISTORY_TARGET_USERS+"</a>");return a},vh_basic:function(a,d,e){return Ext.ucf.htmlEscape(a)},dispDetail:function(a,d){var e=function(a){a=new Ext.FormPanel({labelWidth:30,frame:!1,width:900,layout:"fit",items:[{xtype:"fieldset",autoHeight:!0,autoWidth:!0,defaults:{width:600,height:400},defaultType:"textarea",items:[{fieldLabel:"",name:"text_data",value:a,readOnly:!0}]}],buttons:[{text:_msg.VMSG_CLOSE,
handler:function(){e.close()}}]});var b="";"contents"==d&&(b=_msg.HISTORY_CONTENTS);"log_text"==d&&(b=_msg.LOG);"target_user_ids"==d&&(b=_msg.HISTORY_TARGET_USERS);var e=new Ext.Window({title:b,layout:"fit",modal:!0,width:700,height:500,plain:!0,autoDestory:!0,items:a});e.show();e.dd.constrainTo(Ext.getBody())},f=function(a){void 0!=a.responseText&&""!=a.responseText&&(a=$.parseJSON(a.responseText),0==a.code&&(a=a.record[d],"contents"==d&&""!=a?a=JSON.stringify(JSON.parse(a),null,"    "):"target_user_ids"==
d&&""!=a&&(a=a.replace(",","\n")),e(a)))};Ext.Ajax.request({url:_vurl+"businessrule/xtactionhistorydetail",method:"POST",params:{unique_id:a},success:f,failure:f})},dispHistoryWindow:function(a,d){a=Ext.ucf.businessrule.action.createHistoryGrid(a,d);a=new Ext.Window({layout:"fit",modal:!0,width:700,height:500,plain:!0,autoDestory:!0,items:a});a.show();a.dd.constrainTo(Ext.getBody())},createHistoryGrid:function(a,d){var e=new Ext.data.Store({reader:new Ext.data.JsonReader({idProperty:"unique_id",root:"records",
totalProperty:"all_count"},Ext.ucf.businessrule.action.createHistoryRecord()),url:_vurl+"businessrule/xtactionhistorylist",autoDestroy:!0});if("undefined"==typeof a||""==a)e.on("load",function(a,b,c){Ext.each(b,function(a){Ext.ucf.field.createPlaneText("businessrule_unique_id_"+a.get("unique_id"),a.get("businessrule_unique_id"),Ext.ucf.businessrule.viewHelper,"businessrule_unique_id").render("FIELD_businessrule_unique_id_"+a.get("unique_id"))})});var f=function(){return{start:0,limit:10,sk_businessrule_unique_id:a,
sk_trigger_unique_id:d}},b=function(){Ext.ucf.search(!1,e,f,"")},c=new Ext.Button({iconCls:"reflesh",handler:b}),g=new Ext.PagingToolbar({pageSize:10,store:e,displayInfo:!0,displayMsg:_msg.PAGING_BAR,emptyMsg:_msg.NO_DISP_DATA,items:["->"]});c=new Ext.Toolbar({items:[c]});var k=[];k.push({header:_msg.HISTORY_ESTIMATEDDATETIME,dataIndex:"estimated_datetime",width:70,sortable:!1,renderer:Ext.ucf.businessrule.action.vh_basic});k.push({header:_msg.HISTORY_EXECUTEDATETIME,dataIndex:"execute_datetime",
width:70,sortable:!1,renderer:Ext.ucf.businessrule.action.vh_basic});"undefined"!=typeof a&&""!=a||k.push({header:_msg.HISTORY_BUSINESSRULE_ID,dataIndex:"businessrule_unique_id",width:150,sortable:!1,renderer:Ext.ucf.businessrule.action.vh_businessrule_unique_id});k.push({header:_msg.HISTORY_CHANNELKIND,dataIndex:"channel_kind",width:70,sortable:!1,renderer:Ext.ucf.businessrule.action.vh_channel_kind});k.push({header:_msg.HISTORY_STATUS,dataIndex:"status",width:50,sortable:!1,renderer:Ext.ucf.businessrule.action.vh_status});
k.push({header:_msg.HISTORY_CONTENTS,dataIndex:"contents",align:"center",width:40,sortable:!1,renderer:Ext.ucf.businessrule.action.vh_contents});k.push({header:_msg.HISTORY_TARGET_USERS,dataIndex:"target_user_ids",align:"center",width:40,sortable:!1,renderer:Ext.ucf.businessrule.action.vh_target_user_ids});k.push({header:_msg.LOG,dataIndex:"log_text",align:"center",width:40,sortable:!1,renderer:Ext.ucf.businessrule.action.vh_log_text});k=new Ext.grid.ColumnModel({columns:k});g=new Ext.grid.GridPanel({store:e,
region:"center",columnLines:!0,loadMask:!0,viewConfig:{forceFit:!0},stripeRows:!0,bbar:g,tbar:c,cm:k});return new Ext.Panel({collapsible:!1,title:_msg.VMSG_ACTION_HISTORY,layout:"border",waitMsgTarget:!0,monitorResize:!0,layoutConfig:{columns:1},listeners:{afterRender:function(){b()}},height:320,items:[g]})},init:function(){}}}();
