(function(){function l(e,b,l,v){var a,w,f,r,k,s,p,x,y,m,z,A,B,C,q;b=b||{};void 0!==b.wrap_line_length&&0!==parseInt(b.wrap_line_length,10)||void 0===b.max_char||0===parseInt(b.max_char,10)||(b.wrap_line_length=b.max_char);w=void 0===b.indent_inner_html?!1:b.indent_inner_html;f=void 0===b.indent_size?4:parseInt(b.indent_size,10);r=void 0===b.indent_char?" ":b.indent_char;s=void 0===b.brace_style?"collapse":b.brace_style;k=0===parseInt(b.wrap_line_length,10)?32786:parseInt(b.wrap_line_length||250,10);
p=b.unformatted||"a span img bdo em strong dfn code samp kbd var cite abbr acronym q sub sup tt i b big small u s strike font ins del pre address dt h1 h2 h3 h4 h5 h6 textarea".split(" ");y=(x=void 0===b.preserve_newlines?!0:b.preserve_newlines)?isNaN(parseInt(b.max_preserve_newlines,10))?32786:parseInt(b.max_preserve_newlines,10):0;m=void 0===b.indent_handlebars?!1:b.indent_handlebars;z=void 0===b.wrap_attributes?"auto":b.wrap_attributes;A=void 0===b.wrap_attributes_indent_size?f:parseInt(b.wrap_attributes_indent_size,
10)||f;B=void 0===b.end_with_newline?!1:b.end_with_newline;C="object"==typeof b.extra_liners&&b.extra_liners?b.extra_liners.concat():"string"===typeof b.extra_liners?b.extra_liners.split(","):["head","body","/html"];q=b.eol?b.eol:"\n";b.indent_with_tabs&&(r="\t",f=1);q=q.replace(/\\r/,"\r").replace(/\\n/,"\n");a=new function(){this.pos=0;this.token="";this.current_mode="CONTENT";this.tags={parent:"parent1",parentcount:1,parent1:""};this.token_text=this.last_token=this.last_text=this.token_type=this.tag_type=
"";this.newlines=0;this.indent_content=w;this.Utils={whitespace:["\n","\r","\t"," "],single_token:"br input link meta source !doctype basefont base area hr wbr param img isindex embed".split(" "),extra_liners:C,in_array:function(d,a){for(var c=0;c<a.length;c++)if(d===a[c])return!0;return!1}};this.is_whitespace=function(d){for(;0<d.length;d++)if(!this.Utils.in_array(d.charAt(0),this.Utils.whitespace))return!1;return!0};this.traverse_whitespace=function(){var d="",d=this.input.charAt(this.pos);if(this.Utils.in_array(d,
this.Utils.whitespace)){for(this.newlines=0;this.Utils.in_array(d,this.Utils.whitespace);)x&&"\n"===d&&this.newlines<=y&&(this.newlines+=1),this.pos++,d=this.input.charAt(this.pos);return!0}return!1};this.space_or_wrap=function(d){this.line_char_count>=this.wrap_line_length?(this.print_newline(!1,d),this.print_indentation(d)):(this.line_char_count++,d.push(" "))};this.get_content=function(){for(var d="",a=[];"<"!==this.input.charAt(this.pos);){if(this.pos>=this.input.length)return a.length?a.join(""):
["","TK_EOF"];if(this.traverse_whitespace())this.space_or_wrap(a);else{if(m)if(d=this.input.substr(this.pos,3),"{{#"===d||"{{/"===d)break;else{if("{{!"===d)return[this.get_tag(),"TK_TAG_HANDLEBARS_COMMENT"];if("{{"===this.input.substr(this.pos,2)&&"{{else}}"===this.get_tag(!0))break}d=this.input.charAt(this.pos);this.pos++;this.line_char_count++;a.push(d)}}return a.length?a.join(""):""};this.get_contents_to=function(d){if(this.pos===this.input.length)return["","TK_EOF"];var a="";d=new RegExp("</"+
d+"\\s*>","igm");d.lastIndex=this.pos;d=(d=d.exec(this.input))?d.index:this.input.length;this.pos<d&&(a=this.input.substring(this.pos,d),this.pos=d);return a};this.record_tag=function(d){this.tags[d+"count"]?this.tags[d+"count"]++:this.tags[d+"count"]=1;this.tags[d+this.tags[d+"count"]]=this.indent_level;this.tags[d+this.tags[d+"count"]+"parent"]=this.tags.parent;this.tags.parent=d+this.tags[d+"count"]};this.retrieve_tag=function(d){if(this.tags[d+"count"]){for(var a=this.tags.parent;a&&d+this.tags[d+
"count"]!==a;)a=this.tags[a+"parent"];a&&(this.indent_level=this.tags[d+this.tags[d+"count"]],this.tags.parent=this.tags[a+"parent"]);delete this.tags[d+this.tags[d+"count"]+"parent"];delete this.tags[d+this.tags[d+"count"]];1===this.tags[d+"count"]?delete this.tags[d+"count"]:this.tags[d+"count"]--}};this.indent_to_tag=function(d){if(this.tags[d+"count"]){for(var a=this.tags.parent;a&&d+this.tags[d+"count"]!==a;)a=this.tags[a+"parent"];a&&(this.indent_level=this.tags[d+this.tags[d+"count"]])}};this.get_tag=
function(a){var b="",c=[],b="",n=!1,e=!0,g,h,f=this.pos,k=this.line_char_count;a=void 0!==a?a:!1;do{if(this.pos>=this.input.length)return a&&(this.pos=f,this.line_char_count=k),c.length?c.join(""):["","TK_EOF"];b=this.input.charAt(this.pos);this.pos++;if(this.Utils.in_array(b,this.Utils.whitespace))n=!0;else{if("'"===b||'"'===b)b+=this.get_unformatted(b),n=!0;"="===b&&(n=!1);if(c.length&&"="!==c[c.length-1]&&">"!==b&&n){this.space_or_wrap(c);n=!1;if(!e&&"force"===z&&"/"!==b){this.print_newline(!0,
c);this.print_indentation(c);for(var l=0;l<A;l++)c.push(r)}for(l=0;l<c.length;l++)if(" "===c[l]){e=!1;break}}m&&"<"===h&&"{{"===b+this.input.charAt(this.pos)&&(b+=this.get_unformatted("}}"),c.length&&" "!==c[c.length-1]&&"<"!==c[c.length-1]&&(b=" "+b),n=!0);"<"!==b||h||(g=this.pos-1,h="<");m&&!h&&2<=c.length&&"{"===c[c.length-1]&&"{"===c[c.length-2]&&(g="#"===b||"/"===b||"!"===b?this.pos-3:this.pos-2,h="{");this.line_char_count++;c.push(b);if(c[1]&&("!"===c[1]||"?"===c[1]||"%"===c[1])){c=[this.get_comment(g)];
break}if(m&&c[1]&&"{"===c[1]&&c[2]&&"!"===c[2]){c=[this.get_comment(g)];break}if(m&&"{"===h&&2<c.length&&"}"===c[c.length-2]&&"}"===c[c.length-1])break}}while(">"!==b);g=c.join("");h=-1!==g.indexOf(" ")?g.indexOf(" "):"{"===g.charAt(0)?g.indexOf("}"):g.indexOf(">");b="<"!==g.charAt(0)&&m?"#"===g.charAt(2)?3:2:1;h=g.substring(b,h).toLowerCase();"/"===g.charAt(g.length-2)||this.Utils.in_array(h,this.Utils.single_token)?a||(this.tag_type="SINGLE"):m&&"{"===g.charAt(0)&&"else"===h?a||(this.indent_to_tag("if"),
this.tag_type="HANDLEBARS_ELSE",this.indent_content=!0,this.traverse_whitespace()):this.is_unformatted(h,p)?(b=this.get_unformatted("</"+h+">",g),c.push(b),this.tag_type="SINGLE"):"script"===h&&(-1===g.search("type")||-1<g.search("type")&&-1<g.search(/\b(text|application)\/(x-)?(javascript|ecmascript|jscript|livescript)/))?a||(this.record_tag(h),this.tag_type="SCRIPT"):"style"===h&&(-1===g.search("type")||-1<g.search("type")&&-1<g.search("text/css"))?a||(this.record_tag(h),this.tag_type="STYLE"):
"!"===h.charAt(0)?a||(this.tag_type="SINGLE",this.traverse_whitespace()):a||("/"===h.charAt(0)?(this.retrieve_tag(h.substring(1)),this.tag_type="END"):(this.record_tag(h),"html"!==h.toLowerCase()&&(this.indent_content=!0),this.tag_type="START"),this.traverse_whitespace()&&this.space_or_wrap(c),this.Utils.in_array(h,this.Utils.extra_liners)&&(this.print_newline(!1,this.output),this.output.length&&"\n"!==this.output[this.output.length-2]&&this.print_newline(!0,this.output)));a&&(this.pos=f,this.line_char_count=
k);return c.join("")};this.get_comment=function(a){var b="",c=">",e=!1;this.pos=a;input_char=this.input.charAt(this.pos);for(this.pos++;this.pos<=this.input.length;){b+=input_char;if(b.charAt(b.length-1)===c.charAt(c.length-1)&&-1!==b.indexOf(c))break;!e&&10>b.length&&(0===b.indexOf("<![if")?(c="<![endif]>",e=!0):0===b.indexOf("<![cdata[")?(c="]]\x3e",e=!0):0===b.indexOf("<![")?(c="]>",e=!0):0===b.indexOf("\x3c!--")?(c="--\x3e",e=!0):0===b.indexOf("{{!")?(c="}}",e=!0):0===b.indexOf("<?")?(c="?>",
e=!0):0===b.indexOf("<%")&&(c="%>",e=!0));input_char=this.input.charAt(this.pos);this.pos++}return b};this.get_unformatted=function(a,b){if(b&&-1!==b.toLowerCase().indexOf(a))return"";var c="",e="",f=0,g=!0;do{if(this.pos>=this.input.length)break;c=this.input.charAt(this.pos);this.pos++;if(this.Utils.in_array(c,this.Utils.whitespace)){if(!g){this.line_char_count--;continue}if("\n"===c||"\r"===c){e+="\n";this.line_char_count=0;continue}}e+=c;this.line_char_count++;g=!0;m&&"{"===c&&e.length&&"{"===
e.charAt(e.length-2)&&(e+=this.get_unformatted("}}"),f=e.length)}while(-1===e.toLowerCase().indexOf(a,f));return e};this.get_token=function(){var a;if("TK_TAG_SCRIPT"===this.last_token||"TK_TAG_STYLE"===this.last_token){var b=this.last_token.substr(7);a=this.get_contents_to(b);return"string"!==typeof a?a:[a,"TK_"+b]}if("CONTENT"===this.current_mode)return a=this.get_content(),"string"!==typeof a?a:[a,"TK_CONTENT"];if("TAG"===this.current_mode){a=this.get_tag();if("string"!==typeof a)return a;b="TK_TAG_"+
this.tag_type;if("<tbody>"===a||"</tbody>"===a)b="TK_TAG_"+this.tag_type+"_CONTINUE";return[a,b]}};this.get_full_indent=function(a){a=this.indent_level+a||0;return 1>a?"":Array(a+1).join(this.indent_string)};this.is_unformatted=function(a,b){if(!this.Utils.in_array(a,b))return!1;if("a"!==a.toLowerCase()||!this.Utils.in_array("a",b))return!0;var c=(this.get_tag(!0)||"").match(/^\s*<\s*\/?([a-z]*)\s*[^>]*>\s*$/);return!c||this.Utils.in_array(c,b)?!0:!1};this.printer=function(a,b,c,e,f){this.input=a||
"";this.input=this.input.replace(/\r\n|[\r\u2028\u2029]/g,"\n");this.output=[];this.indent_character=b;this.indent_string="";this.indent_size=c;this.brace_style=f;this.indent_level=0;this.wrap_line_length=e;for(a=this.line_char_count=0;a<this.indent_size;a++)this.indent_string+=this.indent_character;this.print_newline=function(a,b){this.line_char_count=0;b&&b.length&&(a||"\n"!==b[b.length-1])&&("\n"!==b[b.length-1]&&(b[b.length-1]=b[b.length-1].replace(/\s+$/g,"")),b.push("\n"))};this.print_indentation=
function(a){for(var b=0;b<this.indent_level;b++)a.push(this.indent_string),this.line_char_count+=this.indent_string.length};this.print_token=function(a){if(!this.is_whitespace(a)||this.output.length)(a||""!==a)&&this.output.length&&"\n"===this.output[this.output.length-1]&&(this.print_indentation(this.output),a=a.replace(/^\s+/g,"")),this.print_token_raw(a)};this.print_token_raw=function(a){0<this.newlines&&(a=a.replace(/\s+$/g,""));a&&""!==a&&(1<a.length&&"\n"===a.charAt(a.length-1)?(this.output.push(a.slice(0,
-1)),this.print_newline(!1,this.output)):this.output.push(a));for(a=0;a<this.newlines;a++)this.print_newline(0<a,this.output);this.newlines=0};this.indent=function(){this.indent_level++};this.unindent=function(){0<this.indent_level&&this.indent_level--}};return this};for(a.printer(e,r,f,k,s);;){e=a.get_token();a.token_text=e[0];a.token_type=e[1];if("TK_EOF"===a.token_type)break;switch(a.token_type){case "TK_TAG_START_CONTINUE":a.current_mode="CONTENT";break;case "TK_TAG_END_CONTINUE":"TK_CONTENT"===
a.last_token&&""===a.last_text&&(e=a.token_text.match(/\w+/)[0],f=null,a.output.length&&(f=a.output[a.output.length-1].match(/(?:<|{{#)\s*(\w+)/)),(null===f||f[1]!==e&&!a.Utils.in_array(f[1],p))&&a.print_newline(!1,a.output));a.current_mode="CONTENT";break;case "TK_TAG_START":a.print_newline(!1,a.output);a.print_token(a.token_text);a.indent_content&&(a.indent(),a.indent_content=!1);a.current_mode="CONTENT";break;case "TK_TAG_STYLE":case "TK_TAG_SCRIPT":a.print_newline(!1,a.output);a.print_token(a.token_text);
a.current_mode="CONTENT";break;case "TK_TAG_END":"TK_CONTENT"===a.last_token&&""===a.last_text&&(e=a.token_text.match(/\w+/)[0],f=null,a.output.length&&(f=a.output[a.output.length-1].match(/(?:<|{{#)\s*(\w+)/)),(null===f||f[1]!==e&&!a.Utils.in_array(f[1],p))&&a.print_newline(!1,a.output));a.print_token(a.token_text);a.current_mode="CONTENT";break;case "TK_TAG_SINGLE":(e=a.token_text.match(/^\s*<([a-z-]+)/i))&&a.Utils.in_array(e[1],p)||a.print_newline(!1,a.output);a.print_token(a.token_text);a.current_mode=
"CONTENT";break;case "TK_TAG_HANDLEBARS_ELSE":a.print_token(a.token_text);a.indent_content&&(a.indent(),a.indent_content=!1);a.current_mode="CONTENT";break;case "TK_TAG_HANDLEBARS_COMMENT":a.print_token(a.token_text);a.current_mode="TAG";break;case "TK_CONTENT":a.print_token(a.token_text);a.current_mode="TAG";break;case "TK_STYLE":case "TK_SCRIPT":if(""!==a.token_text){a.print_newline(!1,a.output);e=a.token_text;var t;k=1;"TK_SCRIPT"===a.token_type?t="function"===typeof l&&l:"TK_STYLE"===a.token_type&&
(t="function"===typeof v&&v);"keep"===b.indent_scripts?k=0:"separate"===b.indent_scripts&&(k=-a.indent_level);f=a.get_full_indent(k);t?(k=function(){this.eol="\n"},k.prototype=b,k=new k,e=t(e.replace(/^\s*/,f),k)):(s=e.match(/^\s*/)[0].match(/[^\n\r]*$/)[0].split(a.indent_string).length-1,k=a.get_full_indent(k-s),e=e.replace(/^\s*/,f).replace(/\r\n|\r|\n/g,"\n"+k).replace(/\s+$/,""));e&&(a.print_token_raw(e),a.print_newline(!0,a.output))}a.current_mode="TAG";break;default:""!==a.token_text&&a.print_token(a.token_text)}a.last_token=
a.token_type;a.last_text=a.token_text}b=a.output.join("").replace(/[\r\n\t ]+$/,"");B&&(b+="\n");"\n"!=q&&(b=b.replace(/[\n]/g,q));return b}if("function"===typeof define&&define.amd)define(["require","./beautify","./beautify-css"],function(e){var b=e("./beautify"),u=e("./beautify-css");return{html_beautify:function(e,a){return l(e,a,b.js_beautify,u.css_beautify)}}});else if("undefined"!==typeof exports){var u=require("./beautify.js"),D=require("./beautify-css.js");exports.html_beautify=function(e,
b){return l(e,b,u.js_beautify,D.css_beautify)}}else"undefined"!==typeof window?window.html_beautify=function(e,b){return l(e,b,window.js_beautify,window.css_beautify)}:"undefined"!==typeof global&&(global.html_beautify=function(e,b){return l(e,b,global.js_beautify,global.css_beautify)})})();
