var DEBUG_MODE=!1;function debugLog(a){window.console&&window.console.log&&!0===DEBUG_MODE&&window.console.log(a)}
(function(a){var b=a.Base64,c;if("undefined"!==typeof module&&module.exports)try{c=require("buffer").Buffer}catch(e){}var g=function(a){for(var b={},d=0,c=a.length;d<c;d++)b[a.charAt(d)]=d;return b}("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"),d=String.fromCharCode,k=function(a){if(2>a.length){var b=a.charCodeAt(0);return 128>b?a:2048>b?d(192|b>>>6)+d(128|b&63):d(224|b>>>12&15)+d(128|b>>>6&63)+d(128|b&63)}b=65536+1024*(a.charCodeAt(0)-55296)+(a.charCodeAt(1)-56320);return d(240|
b>>>18&7)+d(128|b>>>12&63)+d(128|b>>>6&63)+d(128|b&63)},h=/[\uD800-\uDBFF][\uDC00-\uDFFFF]|[^\x00-\x7F]/g,f=function(a){return a.replace(h,k)},m=function(a){var b=[0,2,1][a.length%3];a=a.charCodeAt(0)<<16|(1<a.length?a.charCodeAt(1):0)<<8|(2<a.length?a.charCodeAt(2):0);return["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(a>>>18),"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(a>>>12&63),2<=b?"=":"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(a>>>
6&63),1<=b?"=":"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(a&63)].join("")},p=a.btoa?function(b){return a.btoa(b)}:function(a){return a.replace(/[\s\S]{1,3}/g,m)},n=c?function(a){return(a.constructor===c.constructor?a:new c(a)).toString("base64")}:function(a){return p(f(a))},l=function(a,b){return b?n(String(a)).replace(/[+\/]/g,function(a){return"+"==a?"-":"_"}).replace(/=/g,""):n(String(a))},u=/[\u00c0-\u00df][\u0080-\u00bf]|[\u00e0-\u00ef][\u0080-\u00bf]{2}|[\u00f0-\u00f7][\u0080-\u00bf]{3}/g,
v=function(a){switch(a.length){case 4:return a=((7&a.charCodeAt(0))<<18|(63&a.charCodeAt(1))<<12|(63&a.charCodeAt(2))<<6|63&a.charCodeAt(3))-65536,d((a>>>10)+55296)+d((a&1023)+56320);case 3:return d((15&a.charCodeAt(0))<<12|(63&a.charCodeAt(1))<<6|63&a.charCodeAt(2));default:return d((31&a.charCodeAt(0))<<6|63&a.charCodeAt(1))}},s=function(a){return a.replace(u,v)},w=function(a){var b=a.length,c=b%4;a=(0<b?g[a.charAt(0)]<<18:0)|(1<b?g[a.charAt(1)]<<12:0)|(2<b?g[a.charAt(2)]<<6:0)|(3<b?g[a.charAt(3)]:
0);a=[d(a>>>16),d(a>>>8&255),d(a&255)];a.length-=[0,0,2,1][c];return a.join("")},t=a.atob?function(b){return a.atob(b)}:function(a){return a.replace(/[\s\S]{1,4}/g,w)},x=c?function(a){return(a.constructor===c.constructor?a:new c(a,"base64")).toString()}:function(a){return s(t(a))},q=function(a){return x(String(a).replace(/[-_]/g,function(a){return"-"==a?"+":"/"}).replace(/[^A-Za-z0-9\+\/]/g,""))};a.Base64={VERSION:"2.1.9",atob:t,btoa:p,fromBase64:q,toBase64:l,utob:f,encode:l,encodeURI:function(a){return l(a,
!0)},btou:s,decode:q,noConflict:function(){var d=a.Base64;a.Base64=b;return d}};if("function"===typeof Object.defineProperty){var r=function(a){return{value:a,enumerable:!1,writable:!0,configurable:!0}};a.Base64.extendString=function(){Object.defineProperty(String.prototype,"fromBase64",r(function(){return q(this)}));Object.defineProperty(String.prototype,"toBase64",r(function(a){return l(this,a)}));Object.defineProperty(String.prototype,"toBase64URI",r(function(){return l(this,!0)}))}}a.Meteor&&
(Base64=a.Base64)})(this);var hasOwnProperty=Object.prototype.hasOwnProperty;function isEmpty(a){if(null==a)return!0;if(0<a.length)return!1;if(0===a.length)return!0;for(var b in a)if(hasOwnProperty.call(a,b))return!1;return!0}
Array.prototype.keySort=function(a){a=a||{};var b=function(a,b,c){c=null!==c?c:1;return a==b?0:a>b?1*c:-1*c},c=function(a){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b}(a);if(!c)return this.sort(b);for(var e in a)a[e]="desc"==a[e]||-1==a[e]?-1:"skip"==a[e]||0===a[e]?0:1;this.sort(function(e,d){for(var k=0,h=0;0===k&&h<c;){var f;a:{f=a;var m=h,p=0,n=void 0;for(n in f)if(f.hasOwnProperty(n)){if(p==m){f=n;break a}p++}f=!1}f&&(k=b(e[f],d[f],a[f]),h++)}return k});return this};
Array.prototype.indexOfObject=function(a){for(var b=0;b<this.length;b++)if(JSON.stringify(this[b])===JSON.stringify(a))return b};function sortArrOfObjectsByParam(a,b,c){void 0==c&&(c=!0);c?a.sort(function(a,c){return a[b]>c[b]}):a.sort(function(a,c){return a[b]<c[b]})}function clone(a){return JSON.parse(JSON.stringify(a))}function testJsonIsOk(a){try{return JSON.parse(JSON.stringify(a)),!0}catch(b){return debugLog("_____ERROR: "+b.message+"_____"),!1}}
function IsNumeric(a){return!isNaN(parseFloat(a))&&isFinite(a)}function IsDate(a){a=new Date(a);return"NaN"!=a.toString()&&"Invalid Date"!=a}function removeAllScriptTags(a){var b=$(document.createElement("div"));b.html(a);b.find("script").remove();return b.html()}function escapeHtml(a){return null==a?null:a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
function unescapeHtml(a){return null==a?null:a.replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&#039;/g,"'")}function escapeAndEncodeHtml(a){return null==a?null:a=encodeURIComponent(a)}function unescapeAndDecodeHtml(a){return null==a?null:a=decodeURIComponent(a)}function getValFromNodeAttribute(a){return"value"in a?a.value:"nodeValue"in a?a.nodeValue:""}ObjectsTemporary=function(){this.items=[];this.active=-1};
ObjectsTemporary.prototype.get=function(a){with(this)return"undefined"==typeof a&&(a=this.active),0<this.items.length?this.items[a]:null};ObjectsTemporary.prototype.set=function(a){with(this){if("undefined"==typeof a||"object"!=typeof a)return!1;this.active+=1;this.items.push(a);return!0}};ObjectsTemporary.prototype.destroy=function(a){with(this)items=[],active=-1};
RefactorCode={parent:null,numTab:1,result:"",arrCnt:["tbody"],arrOts:["input","span","label"],checkTagNameIsOts:function(a){for(var b=0;b<RefactorCode.arrOts.length;b++)if(RefactorCode.arrOts[b]==a)return!0;return!1},checkTagNameIsContinue:function(a){for(var b=0;b<RefactorCode.arrCnt.length;b++)if(RefactorCode.arrCnt[b]==a)return!0;return!1},getTabString:function(a){for(var b="",c=0;c<a;c++)b+="  ";return b},getInnerText:function(a){a=$(a).clone();$.each($(a).children(),function(){$(this).remove()});
return $(a).text()},getChildren:function(a,b){for(var c=$(a).children(),e=0;e<c.length;e++){var g=c[e],d=g.tagName.toLowerCase(),k=RefactorCode.checkTagNameIsContinue(d);!0==k&&(b-=1);var h=RefactorCode.getTabString(b);if("textarea"==d){RefactorCode.result+=h;RefactorCode.result+="<"+d;try{$.each(g.attributes,function(){RefactorCode.result+=" "+this.name+'="'+this.value+'"'})}catch(f){}RefactorCode.result+=">";RefactorCode.result+=$(g).val();RefactorCode.result+="</"+d+">";RefactorCode.result+="\n"}else if("br"==
d){var m="";try{$.each(g.attributes,function(){m+=" "+this.name+'="'+this.value+'"'})}catch(p){}RefactorCode.result+=h+"<br"+m+">\n"}else{if(!1==k){RefactorCode.result+=h;RefactorCode.result+="<"+d;try{$.each(g.attributes,function(){RefactorCode.result+=" "+this.name+'="'+this.value+'"'})}catch(n){}RefactorCode.result+=">\n"}var l=RefactorCode.getInnerText(g);""!=l.trim()&&(RefactorCode.result=!1==k?RefactorCode.result+(h+"  "+l):RefactorCode.result+("  "+l),RefactorCode.result+="\n");RefactorCode.getChildren(g,
b+1);!1==k&&(RefactorCode.result+=h,RefactorCode.result+="</"+d+">",RefactorCode.result+="\n")}}},init:function(a,b){RefactorCode.parent=a.parent;RefactorCode.numTab=1;RefactorCode.result="";RefactorCode.test=!1;"undefined"==typeof b&&(b=!0);b||RefactorCode.parent.append(MainLayout.sateraito_script.outerHTML);RefactorCode.result=beautify($(RefactorCode.parent).html())}};
function beautify(a,b,c){var e={},e={indent_size:2,indent_char:" ",eol:"\n",indent_level:0,indent_with_tabs:!1,preserve_newlines:!1,max_preserve_newlines:0,jslint_happy:!1,space_after_anon_function:!1,brace_style:"collapse",keep_array_indentation:!1,keep_function_indentation:!1,space_before_conditional:!0,break_chained_methods:!1,eval_code:!1,unescape_strings:!1,wrap_line_length:0,wrap_attributes:"auto",wrap_attributes_indent_size:2,end_with_newline:!1};return(b?js_beautify(a,e):c?css_beautify(a,
e):html_beautify(a,e)).replace(/&#10;/g,"\r\n").replace(/&#9;/g,"\t")}
MiniMessage={message:null,fontSize:12,initMessageArea:function(a){"undefined"!=typeof a&&(MiniMessage.fontSize=a);a='<div id="mini_message" style="position:absolute; top:0px; left:0px; width:200px; text-align:center; z-index:10000;"></div>';$("body").append(a);a=$(window).width();var b=$("#mini_message").width();$("#mini_message").css("left",""+(a/2-b/2)+"px")},clearMessage:function(){$("#mini_message").html("")},showLoadingMessage:function(a){"undefined"==typeof a&&(a=MyLang.getMsg("LOADING"));$("#mini_message").html("");
$("#mini_message").css("width","250px");var b=$("#mini_message").parent().width(),c=$("#mini_message").width();$("#mini_message").css("left",""+(b/2-c/2)+"px");$("#mini_message").text(a).css("width","250px").css("font-size","1.4em").css("font-weight","bold").css("background-color","lemonchiffon").css("text-align","center")},showNormalMiniMessage:function(a,b){"undefined"==typeof b&&(b=3E3);$("#mini_message").html("");$("#mini_message").css("width","350px");var c=$("#mini_message").parent().width(),
e=$("#mini_message").width();$("#mini_message").css("left",""+(c/2-e/2)+"px");$("#mini_message").text(a).css("font-size","1.4em").css("width","350px").css("font-weight","bold").css("background-color","lemonchiffon").css("text-align","center");(function(){$("#mini_message").html("").css("width","0px")}).defer(b)},showErrMiniMessage:function(a){$("#mini_message").html("");$("#mini_message").css("width","400px");var b=$("#mini_message").parent().width(),c=$("#mini_message").width();$("#mini_message").css("left",
""+(b/2-c/2)+"px");$("#mini_message").text(a).css("font-size","1.2em").css("width","400px").css("font-weight","bold").css("background-color","pink").css("text-align","center");(function(){$("#mini_message").html("").css("width","0px")}).defer(3E3)}};
